///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace B_EXOPV_001.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Pruefung_Stapel recording.
    /// </summary>
    [TestModule("314970cf-8b90-4c63-a0f9-476fde2ad738", ModuleType.Recording, 1)]
    public partial class Verbuchung_Kassabuch_ER_BUCH : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::B_EXOPV_001.B_EXOPV_001Repository repository.
        /// </summary>
        public static global::B_EXOPV_001.B_EXOPV_001Repository repo = global::B_EXOPV_001.B_EXOPV_001Repository.Instance;

        static Verbuchung_Kassabuch_ER_BUCH instance = new Verbuchung_Kassabuch_ER_BUCH();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Verbuchung_Kassabuch_ER_BUCH()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Verbuchung_Kassabuch_ER_BUCH Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Stapel1_Kassabuch.
        /// </summary>
        [TestVariable("a08eadc0-dbe6-458c-92bf-e0ffe26a8422")]
        public string Stapel1_Kassabuch
        {
            get { return repo.Stapel1_Kassabuch; }
            set { repo.Stapel1_Kassabuch = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Stapel2_ERBuch.
        /// </summary>
        [TestVariable("6c238a9a-1ff1-4fc6-8112-469f47ca693a")]
        public string Stapel2_ERBuch
        {
            get { return repo.Stapel2_ERBuch; }
            set { repo.Stapel2_ERBuch = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Form100ExterneBuchungenVerbuchen.TitleBar100ExterneBuchungenVerbuche'.", repo.Form100ExterneBuchungenVerbuchen.TitleBar100ExterneBuchungenVerbucheInfo, new RecordItemIndex(0));
            Validate.Exists(repo.Form100ExterneBuchungenVerbuchen.TitleBar100ExterneBuchungenVerbucheInfo);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form100ExterneBuchungenVerbuchen.Tabelle_Zeilen_mit_Variablen_Stapel1_Kassabuch_Stapel2_ERBuch.Zeile_mit_Stapel1_Kassabuch_14_01_2020.Column0_Stapel1' at Center.", repo.Form100ExterneBuchungenVerbuchen.Tabelle_Zeilen_mit_Variablen_Stapel1_Kassabuch_Stapel2_ERBuch.Zeile_mit_Stapel1_Kassabuch_14_01_2020.Column0_Stapel1Info, new RecordItemIndex(1));
            repo.Form100ExterneBuchungenVerbuchen.Tabelle_Zeilen_mit_Variablen_Stapel1_Kassabuch_Stapel2_ERBuch.Zeile_mit_Stapel1_Kassabuch_14_01_2020.Column0_Stapel1.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}'.", new RecordItemIndex(2));
            Keyboard.Press("{LControlKey down}");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form100ExterneBuchungenVerbuchen.Tabelle_Zeilen_mit_Variablen_Stapel1_Kassabuch_Stapel2_ERBuch.Zeile_mit_Stapel2_ERBuch_15_01_2020.Column0_Stapel2' at Center.", repo.Form100ExterneBuchungenVerbuchen.Tabelle_Zeilen_mit_Variablen_Stapel1_Kassabuch_Stapel2_ERBuch.Zeile_mit_Stapel2_ERBuch_15_01_2020.Column0_Stapel2Info, new RecordItemIndex(3));
            repo.Form100ExterneBuchungenVerbuchen.Tabelle_Zeilen_mit_Variablen_Stapel1_Kassabuch_Stapel2_ERBuch.Zeile_mit_Stapel2_ERBuch_15_01_2020.Column0_Stapel2.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey up}'.", new RecordItemIndex(4));
            Keyboard.Press("{LControlKey up}");
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(5));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Form100ExterneBuchungenVerbuchen.PbCommonVerbuchen' at Center.", repo.Form100ExterneBuchungenVerbuchen.PbCommonVerbuchenInfo, new RecordItemIndex(6));
            repo.Form100ExterneBuchungenVerbuchen.PbCommonVerbuchen.Click();
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 2m to exist. Associated repository item: 'DlgMessageBox.FakturenPruefung'", repo.DlgMessageBox.FakturenPruefungInfo, new ActionTimeout(120000), new RecordItemIndex(7));
            repo.DlgMessageBox.FakturenPruefungInfo.WaitForExists(120000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Belege wurden verbucht ! ') on item 'DlgMessageBox.LabelMeldungstext'.", repo.DlgMessageBox.LabelMeldungstextInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.DlgMessageBox.LabelMeldungstextInfo, "Text", "Belege wurden verbucht ! ");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DlgMessageBox.Button0' at Center.", repo.DlgMessageBox.Button0Info, new RecordItemIndex(9));
            repo.DlgMessageBox.Button0.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
