name: API Automation
trigger:
- main

resources:
- repo: self

pool:
  name: Automation
  demands:
   - agent.name -equals DGA1APP03RNSQA

steps:
  - task: DownloadBuildArtifacts@1
    inputs:
     buildType: 'specific'
     project: '1692ec27-30a7-44ac-bb45-41f0b3ec9f01'
     pipeline: '99'
     buildVersionToDownload: 'specific'
     buildId: '$(buildId)'
     downloadType: 'single'
     artifactName: 'RS2Build'
     downloadPath: '$(System.ArtifactsDirectory)'

  - task: PowerShell@2
    displayName: 'Run Service Host'
    inputs:
     targetType: 'inline'
     script: |
       Start-Process -FilePath "$(System.DefaultWorkingDirectory)/API_Automation_Cypress/BatchFile/ServiceHost.bat" -WindowStyle Hidden

  - task: CmdLine@2
    displayName: 'NPM initialization'
    inputs:
      script: |
       npm install
       npm i   
      workingDirectory: '$(System.DefaultWorkingDirectory)/API_Automation_Cypress/Modulewise_TestCases'

  - task: BatchScript@1
    displayName: 'Run Cypress Scripts'
    inputs:
     filename: '$(System.DefaultWorkingDirectory)/API_Automation_Cypress/BatchFile/RunScripts.bat'

  - task: ArchiveFiles@2
    inputs:
     rootFolderOrFile: '$(System.DefaultWorkingDirectory)\API_Automation_Cypress\Modulewise_TestCases\cypress\reports'
     includeRootFolder: true
     archiveType: 'zip'
     archiveFile: '$(System.DefaultWorkingDirectory)\API_Automation_Cypress\Modulewise_TestCases\cypress\reports.zip'
     replaceExistingArchive: true
