///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace B_KTO_001
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the B_KTO_001Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0575da86-53fb-47ca-8967-8dd651d8ebb9")]
    public partial class B_KTO_001Repository : RepoGenBaseFolder
    {
        static B_KTO_001Repository instance = new B_KTO_001Repository();
        B_KTO_001RepositoryFolders.FrmKtoAppFolder _frmkto;
        B_KTO_001RepositoryFolders.DlgMessageBoxAppFolder _dlgmessagebox;

        /// <summary>
        /// Gets the singleton class instance representing the B_KTO_001Repository element repository.
        /// </summary>
        [RepositoryFolder("0575da86-53fb-47ca-8967-8dd651d8ebb9")]
        public static B_KTO_001Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public B_KTO_001Repository() 
            : base("B_KTO_001Repository", "/", null, 0, false, "0575da86-53fb-47ca-8967-8dd651d8ebb9", ".\\RepositoryImages\\B_KTO_001Repository0575da86.rximgres")
        {
            _frmkto = new B_KTO_001RepositoryFolders.FrmKtoAppFolder(this);
            _dlgmessagebox = new B_KTO_001RepositoryFolders.DlgMessageBoxAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0575da86-53fb-47ca-8967-8dd651d8ebb9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FrmKto folder.
        /// </summary>
        [RepositoryFolder("4f43a5e7-dc06-40b2-a408-8a14d096644a")]
        public virtual B_KTO_001RepositoryFolders.FrmKtoAppFolder FrmKto
        {
            get { return _frmkto; }
        }

        /// <summary>
        /// The DlgMessageBox folder.
        /// </summary>
        [RepositoryFolder("e912e587-0744-4a1d-80ab-47a8ff01fac7")]
        public virtual B_KTO_001RepositoryFolders.DlgMessageBoxAppFolder DlgMessageBox
        {
            get { return _dlgmessagebox; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class B_KTO_001RepositoryFolders
    {
        /// <summary>
        /// The FrmKtoAppFolder folder.
        /// </summary>
        [RepositoryFolder("4f43a5e7-dc06-40b2-a408-8a14d096644a")]
        public partial class FrmKtoAppFolder : RepoGenBaseFolder
        {
            B_KTO_001RepositoryFolders.Tab_AllgemeinFolder _tab_allgemein;
            RepoItemInfo _titlebar100sachkontenverwaltenInfo;
            RepoItemInfo _pbdataaccesssaveInfo;
            RepoItemInfo _pbnewInfo;
            RepoItemInfo _rbaktivInfo;
            RepoItemInfo _kontoInfo;
            RepoItemInfo _bezeichnungInfo;
            RepoItemInfo _waehrungInfo;
            RepoItemInfo _tabpageallgemeinInfo;
            RepoItemInfo _tabpagegruppenInfo;
            RepoItemInfo _colktgrcdrow1Info;
            RepoItemInfo _bereicheInfo;
            RepoItemInfo _colktbzkzrow1Info;

            /// <summary>
            /// Creates a new FrmKto  folder.
            /// </summary>
            public FrmKtoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmKto", "/form[@controlname='frmKto']", parentFolder, 30000, null, true, "4f43a5e7-dc06-40b2-a408-8a14d096644a", "")
            {
                _tab_allgemein = new B_KTO_001RepositoryFolders.Tab_AllgemeinFolder(this);
                _titlebar100sachkontenverwaltenInfo = new RepoItemInfo(this, "TitleBar100SachkontenVerwalten", "titlebar[@accessiblerole='TitleBar']", "", 30000, null, "87af4cac-779e-4130-addf-5d05faf0e6d1");
                _pbdataaccesssaveInfo = new RepoItemInfo(this, "PbDataAccessSave", "container[@controlname='RibbonBar']/container[@controlname='DataAccessGroup']/button[@controlname='pbDataAccess_Save']", "", 30000, null, "7d8930c2-8c91-4cee-a935-7b794437b07f");
                _pbnewInfo = new RepoItemInfo(this, "PbNew", "container[@controlname='searchContainer']/form[@controlname='frmSearchPage']/container[@controlname='RibbonBar']/container[@controlname='SearchGroup2']/button[@controlname='pbNew']", "", 30000, null, "8cb95032-ac82-44cf-bf8b-3c6ad6212bc8");
                _rbaktivInfo = new RepoItemInfo(this, "RbAktiv", "container[@controlname='ClientArea']/container[@controlname='groupBox1']/radiobutton[@controlname='rbAktiv']", "", 30000, null, "1de6fd7f-3451-42cd-ac4d-7efbf6d1a005");
                _kontoInfo = new RepoItemInfo(this, "Konto", "container[@controlname='ClientArea']/text[@controlname='dfKto_nr']/text[@accessiblename='Konto']", "", 30000, null, "0894121b-4129-4a6c-844d-987ca981a22d");
                _bezeichnungInfo = new RepoItemInfo(this, "Bezeichnung", "container[@controlname='ClientArea']/text[@controlname='dfKto_bez1']/text[@accessiblename='Bezeichnung']", "", 30000, null, "93ff4f20-c2c8-402a-8b05-aec9479b56b2");
                _waehrungInfo = new RepoItemInfo(this, "Waehrung", "container[@controlname='ClientArea']/text[@controlname='dfWrg_cd']/text[@accessiblename='Währung']", "", 30000, null, "7cf50209-db4d-4fda-83f7-b61e0c2cdb48");
                _tabpageallgemeinInfo = new RepoItemInfo(this, "TabPageAllgemein", "container[@controlname='ClientArea']/tabpagelist[@controlname='picTabs']/tabpage[@accessiblename='&Allgemein']", "", 30000, null, "c2ccf159-ddd7-487d-9260-63c5b738df20");
                _tabpagegruppenInfo = new RepoItemInfo(this, "TabPageGruppen", "container[@controlname='ClientArea']/tabpagelist[@controlname='picTabs']/tabpage[@accessiblename='&Gruppen']", "", 30000, null, "3692b34f-25fe-461b-8bf7-9618e163d890");
                _colktgrcdrow1Info = new RepoItemInfo(this, "ColKtgrCdRow1", "container[@controlname='ClientArea']/tabpagelist[@controlname='picTabs']/tabpage[@controlname='tpGruppen']/container[@controlname='tblKtgz']/element[@controlname='mainGrid']/table[@accessiblename='FlexGrid']/row[@accessiblename='Row 1']/cell[@accessiblename='colKtgr_cd Row 1']", "", 30000, null, "70913db3-6972-4d7f-b330-f8662af8b072");
                _bereicheInfo = new RepoItemInfo(this, "Bereiche", "container[@controlname='ClientArea']/tabpagelist[@controlname='picTabs']/tabpage[@accessiblename='Be&reiche']", "", 30000, null, "d5b4f562-4cea-4343-a30f-0e2106aa769d");
                _colktbzkzrow1Info = new RepoItemInfo(this, "ColKtbzKzRow1", "container[@controlname='ClientArea']/tabpagelist[@controlname='picTabs']/tabpage[@controlname='tpBereiche']/container[@controlname='tblKtbz']/element[@controlname='mainGrid']/table[@accessiblename='FlexGrid']/row[@accessiblename='Row 1']/cell[@accessiblename='colKtbz_kz Row 1']", "", 30000, null, "8bffc19c-4278-4ee0-9702-3f1007a34fe8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4f43a5e7-dc06-40b2-a408-8a14d096644a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4f43a5e7-dc06-40b2-a408-8a14d096644a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar100SachkontenVerwalten item.
            /// </summary>
            [RepositoryItem("87af4cac-779e-4130-addf-5d05faf0e6d1")]
            public virtual Ranorex.TitleBar TitleBar100SachkontenVerwalten
            {
                get
                {
                    return _titlebar100sachkontenverwaltenInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar100SachkontenVerwalten item info.
            /// </summary>
            [RepositoryItemInfo("87af4cac-779e-4130-addf-5d05faf0e6d1")]
            public virtual RepoItemInfo TitleBar100SachkontenVerwaltenInfo
            {
                get
                {
                    return _titlebar100sachkontenverwaltenInfo;
                }
            }

            /// <summary>
            /// The PbDataAccessSave item.
            /// </summary>
            [RepositoryItem("7d8930c2-8c91-4cee-a935-7b794437b07f")]
            public virtual Ranorex.Button PbDataAccessSave
            {
                get
                {
                    return _pbdataaccesssaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PbDataAccessSave item info.
            /// </summary>
            [RepositoryItemInfo("7d8930c2-8c91-4cee-a935-7b794437b07f")]
            public virtual RepoItemInfo PbDataAccessSaveInfo
            {
                get
                {
                    return _pbdataaccesssaveInfo;
                }
            }

            /// <summary>
            /// The PbNew item.
            /// </summary>
            [RepositoryItem("8cb95032-ac82-44cf-bf8b-3c6ad6212bc8")]
            public virtual Ranorex.Button PbNew
            {
                get
                {
                    return _pbnewInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PbNew item info.
            /// </summary>
            [RepositoryItemInfo("8cb95032-ac82-44cf-bf8b-3c6ad6212bc8")]
            public virtual RepoItemInfo PbNewInfo
            {
                get
                {
                    return _pbnewInfo;
                }
            }

            /// <summary>
            /// The RbAktiv item.
            /// </summary>
            [RepositoryItem("1de6fd7f-3451-42cd-ac4d-7efbf6d1a005")]
            public virtual Ranorex.RadioButton RbAktiv
            {
                get
                {
                    return _rbaktivInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RbAktiv item info.
            /// </summary>
            [RepositoryItemInfo("1de6fd7f-3451-42cd-ac4d-7efbf6d1a005")]
            public virtual RepoItemInfo RbAktivInfo
            {
                get
                {
                    return _rbaktivInfo;
                }
            }

            /// <summary>
            /// The Konto item.
            /// </summary>
            [RepositoryItem("0894121b-4129-4a6c-844d-987ca981a22d")]
            public virtual Ranorex.Text Konto
            {
                get
                {
                    return _kontoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Konto item info.
            /// </summary>
            [RepositoryItemInfo("0894121b-4129-4a6c-844d-987ca981a22d")]
            public virtual RepoItemInfo KontoInfo
            {
                get
                {
                    return _kontoInfo;
                }
            }

            /// <summary>
            /// The Bezeichnung item.
            /// </summary>
            [RepositoryItem("93ff4f20-c2c8-402a-8b05-aec9479b56b2")]
            public virtual Ranorex.Text Bezeichnung
            {
                get
                {
                    return _bezeichnungInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Bezeichnung item info.
            /// </summary>
            [RepositoryItemInfo("93ff4f20-c2c8-402a-8b05-aec9479b56b2")]
            public virtual RepoItemInfo BezeichnungInfo
            {
                get
                {
                    return _bezeichnungInfo;
                }
            }

            /// <summary>
            /// The Waehrung item.
            /// </summary>
            [RepositoryItem("7cf50209-db4d-4fda-83f7-b61e0c2cdb48")]
            public virtual Ranorex.Text Waehrung
            {
                get
                {
                    return _waehrungInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Waehrung item info.
            /// </summary>
            [RepositoryItemInfo("7cf50209-db4d-4fda-83f7-b61e0c2cdb48")]
            public virtual RepoItemInfo WaehrungInfo
            {
                get
                {
                    return _waehrungInfo;
                }
            }

            /// <summary>
            /// The TabPageAllgemein item.
            /// </summary>
            [RepositoryItem("c2ccf159-ddd7-487d-9260-63c5b738df20")]
            public virtual Ranorex.TabPage TabPageAllgemein
            {
                get
                {
                    return _tabpageallgemeinInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TabPageAllgemein item info.
            /// </summary>
            [RepositoryItemInfo("c2ccf159-ddd7-487d-9260-63c5b738df20")]
            public virtual RepoItemInfo TabPageAllgemeinInfo
            {
                get
                {
                    return _tabpageallgemeinInfo;
                }
            }

            /// <summary>
            /// The TabPageGruppen item.
            /// </summary>
            [RepositoryItem("3692b34f-25fe-461b-8bf7-9618e163d890")]
            public virtual Ranorex.TabPage TabPageGruppen
            {
                get
                {
                    return _tabpagegruppenInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TabPageGruppen item info.
            /// </summary>
            [RepositoryItemInfo("3692b34f-25fe-461b-8bf7-9618e163d890")]
            public virtual RepoItemInfo TabPageGruppenInfo
            {
                get
                {
                    return _tabpagegruppenInfo;
                }
            }

            /// <summary>
            /// The ColKtgrCdRow1 item.
            /// </summary>
            [RepositoryItem("70913db3-6972-4d7f-b330-f8662af8b072")]
            public virtual Ranorex.Cell ColKtgrCdRow1
            {
                get
                {
                    return _colktgrcdrow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColKtgrCdRow1 item info.
            /// </summary>
            [RepositoryItemInfo("70913db3-6972-4d7f-b330-f8662af8b072")]
            public virtual RepoItemInfo ColKtgrCdRow1Info
            {
                get
                {
                    return _colktgrcdrow1Info;
                }
            }

            /// <summary>
            /// The Bereiche item.
            /// </summary>
            [RepositoryItem("d5b4f562-4cea-4343-a30f-0e2106aa769d")]
            public virtual Ranorex.TabPage Bereiche
            {
                get
                {
                    return _bereicheInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Bereiche item info.
            /// </summary>
            [RepositoryItemInfo("d5b4f562-4cea-4343-a30f-0e2106aa769d")]
            public virtual RepoItemInfo BereicheInfo
            {
                get
                {
                    return _bereicheInfo;
                }
            }

            /// <summary>
            /// The ColKtbzKzRow1 item.
            /// </summary>
            [RepositoryItem("8bffc19c-4278-4ee0-9702-3f1007a34fe8")]
            public virtual Ranorex.Cell ColKtbzKzRow1
            {
                get
                {
                    return _colktbzkzrow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColKtbzKzRow1 item info.
            /// </summary>
            [RepositoryItemInfo("8bffc19c-4278-4ee0-9702-3f1007a34fe8")]
            public virtual RepoItemInfo ColKtbzKzRow1Info
            {
                get
                {
                    return _colktbzkzrow1Info;
                }
            }

            /// <summary>
            /// The Tab_Allgemein folder.
            /// </summary>
            [RepositoryFolder("1b2b94e2-8d85-4024-8136-ef47e2e9b47a")]
            public virtual B_KTO_001RepositoryFolders.Tab_AllgemeinFolder Tab_Allgemein
            {
                get { return _tab_allgemein; }
            }
        }

        /// <summary>
        /// The Tab_AllgemeinFolder folder.
        /// </summary>
        [RepositoryFolder("1b2b94e2-8d85-4024-8136-ef47e2e9b47a")]
        public partial class Tab_AllgemeinFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ustpflichtInfo;
            RepoItemInfo _ustcodeInfo;
            RepoItemInfo _cbktoskontoInfo;

            /// <summary>
            /// Creates a new Tab_Allgemein  folder.
            /// </summary>
            public Tab_AllgemeinFolder(RepoGenBaseFolder parentFolder) :
                    base("Tab_Allgemein", "container/tabpagelist[@controlname='picTabs']/tabpage[@controlname='tpAllgemein']", parentFolder, 30000, null, false, "1b2b94e2-8d85-4024-8136-ef47e2e9b47a", "")
            {
                _ustpflichtInfo = new RepoItemInfo(this, "UstPflicht", "text[@controlname='dfKto_ustmv']/text[@accessiblename='Ust-Pflicht']", "", 30000, null, "9caa3852-95ec-4c3f-b3c4-5d794cfd1a28");
                _ustcodeInfo = new RepoItemInfo(this, "UstCode", "text[@controlname='dfUst_cd']/text[@accessiblename='Ust-Code']", "", 30000, null, "e1152c7e-52fb-4a43-82c1-2fc14b134aef");
                _cbktoskontoInfo = new RepoItemInfo(this, "CbKtoSkonto", "checkbox[@controlname='cbKto_skonto']", "", 30000, null, "e9482024-f2ed-4fa4-91eb-fa3bd0677e9f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1b2b94e2-8d85-4024-8136-ef47e2e9b47a")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1b2b94e2-8d85-4024-8136-ef47e2e9b47a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UstPflicht item.
            /// </summary>
            [RepositoryItem("9caa3852-95ec-4c3f-b3c4-5d794cfd1a28")]
            public virtual Ranorex.Text UstPflicht
            {
                get
                {
                    return _ustpflichtInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UstPflicht item info.
            /// </summary>
            [RepositoryItemInfo("9caa3852-95ec-4c3f-b3c4-5d794cfd1a28")]
            public virtual RepoItemInfo UstPflichtInfo
            {
                get
                {
                    return _ustpflichtInfo;
                }
            }

            /// <summary>
            /// The UstCode item.
            /// </summary>
            [RepositoryItem("e1152c7e-52fb-4a43-82c1-2fc14b134aef")]
            public virtual Ranorex.Text UstCode
            {
                get
                {
                    return _ustcodeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UstCode item info.
            /// </summary>
            [RepositoryItemInfo("e1152c7e-52fb-4a43-82c1-2fc14b134aef")]
            public virtual RepoItemInfo UstCodeInfo
            {
                get
                {
                    return _ustcodeInfo;
                }
            }

            /// <summary>
            /// The CbKtoSkonto item.
            /// </summary>
            [RepositoryItem("e9482024-f2ed-4fa4-91eb-fa3bd0677e9f")]
            public virtual Ranorex.CheckBox CbKtoSkonto
            {
                get
                {
                    return _cbktoskontoInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CbKtoSkonto item info.
            /// </summary>
            [RepositoryItemInfo("e9482024-f2ed-4fa4-91eb-fa3bd0677e9f")]
            public virtual RepoItemInfo CbKtoSkontoInfo
            {
                get
                {
                    return _cbktoskontoInfo;
                }
            }
        }

        /// <summary>
        /// The DlgMessageBoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("e912e587-0744-4a1d-80ab-47a8ff01fac7")]
        public partial class DlgMessageBoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;
            RepoItemInfo _button0Info;
            RepoItemInfo _labelmeldungstextInfo;

            /// <summary>
            /// Creates a new DlgMessageBox  folder.
            /// </summary>
            public DlgMessageBoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DlgMessageBox", "/form[@controlname='dlgMessageBox']", parentFolder, 30000, null, true, "e912e587-0744-4a1d-80ab-47a8ff01fac7", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlname='button1']", "", 30000, null, "ae430006-2abf-4e96-999e-532f4c76cc6b");
                _button0Info = new RepoItemInfo(this, "Button0", "button[@controlname='button0']", "", 30000, null, "2848dc13-e4de-47a8-85e3-01eb8f5dd828");
                _labelmeldungstextInfo = new RepoItemInfo(this, "LabelMeldungstext", "text[@controlname='labelMeldungstext']", "", 30000, null, "89af2a25-55a5-4bc4-bac3-305b4830a5f4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e912e587-0744-4a1d-80ab-47a8ff01fac7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e912e587-0744-4a1d-80ab-47a8ff01fac7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("ae430006-2abf-4e96-999e-532f4c76cc6b")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("ae430006-2abf-4e96-999e-532f4c76cc6b")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The Button0 item.
            /// </summary>
            [RepositoryItem("2848dc13-e4de-47a8-85e3-01eb8f5dd828")]
            public virtual Ranorex.Button Button0
            {
                get
                {
                    return _button0Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button0 item info.
            /// </summary>
            [RepositoryItemInfo("2848dc13-e4de-47a8-85e3-01eb8f5dd828")]
            public virtual RepoItemInfo Button0Info
            {
                get
                {
                    return _button0Info;
                }
            }

            /// <summary>
            /// The LabelMeldungstext item.
            /// </summary>
            [RepositoryItem("89af2a25-55a5-4bc4-bac3-305b4830a5f4")]
            public virtual Ranorex.Text LabelMeldungstext
            {
                get
                {
                    return _labelmeldungstextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LabelMeldungstext item info.
            /// </summary>
            [RepositoryItemInfo("89af2a25-55a5-4bc4-bac3-305b4830a5f4")]
            public virtual RepoItemInfo LabelMeldungstextInfo
            {
                get
                {
                    return _labelmeldungstextInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
