///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace X_MUSTER_002
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the X_MUSTER_002Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("6e0c13fc-9aa7-4a02-a313-a2166c2ee04a")]
    public partial class X_MUSTER_002Repository : RepoGenBaseFolder
    {
        static X_MUSTER_002Repository instance = new X_MUSTER_002Repository();
        X_MUSTER_002RepositoryFolders.UnbenanntEditorAppFolder _unbenannteditor;
        X_MUSTER_002RepositoryFolders.FrmUhrAppFolder _frmuhr;

        /// <summary>
        /// Gets the singleton class instance representing the X_MUSTER_002Repository element repository.
        /// </summary>
        [RepositoryFolder("6e0c13fc-9aa7-4a02-a313-a2166c2ee04a")]
        public static X_MUSTER_002Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public X_MUSTER_002Repository() 
            : base("X_MUSTER_002Repository", "/", null, 0, false, "6e0c13fc-9aa7-4a02-a313-a2166c2ee04a", ".\\RepositoryImages\\X_MUSTER_002Repository6e0c13fc.rximgres")
        {
            _unbenannteditor = new X_MUSTER_002RepositoryFolders.UnbenanntEditorAppFolder(this);
            _frmuhr = new X_MUSTER_002RepositoryFolders.FrmUhrAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("6e0c13fc-9aa7-4a02-a313-a2166c2ee04a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The UnbenanntEditor folder.
        /// </summary>
        [RepositoryFolder("07a5ebc2-f2df-4e9f-aef0-9bebc1470004")]
        public virtual X_MUSTER_002RepositoryFolders.UnbenanntEditorAppFolder UnbenanntEditor
        {
            get { return _unbenannteditor; }
        }

        /// <summary>
        /// The FrmUhr folder.
        /// </summary>
        [RepositoryFolder("b2819dc5-6d4f-4c86-8077-0fdbced80579")]
        public virtual X_MUSTER_002RepositoryFolders.FrmUhrAppFolder FrmUhr
        {
            get { return _frmuhr; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class X_MUSTER_002RepositoryFolders
    {
        /// <summary>
        /// The UnbenanntEditorAppFolder folder.
        /// </summary>
        [RepositoryFolder("07a5ebc2-f2df-4e9f-aef0-9bebc1470004")]
        public partial class UnbenanntEditorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _unbenannteditorInfo;
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new UnbenanntEditor  folder.
            /// </summary>
            public UnbenanntEditorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UnbenanntEditor", "/form[@title='Unbenannt - Editor']", parentFolder, 30000, null, true, "07a5ebc2-f2df-4e9f-aef0-9bebc1470004", "")
            {
                _unbenannteditorInfo = new RepoItemInfo(this, "UnbenanntEditor", "titlebar[@accessiblerole='TitleBar']", "", 30000, null, "ebec5361-e876-4e66-a729-2e4e51576e03");
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", "", 30000, null, "63d0e412-33ea-44fb-afab-d3e3f96f8be2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("07a5ebc2-f2df-4e9f-aef0-9bebc1470004")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("07a5ebc2-f2df-4e9f-aef0-9bebc1470004")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UnbenanntEditor item.
            /// </summary>
            [RepositoryItem("ebec5361-e876-4e66-a729-2e4e51576e03")]
            public virtual Ranorex.TitleBar UnbenanntEditor
            {
                get
                {
                    return _unbenannteditorInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The UnbenanntEditor item info.
            /// </summary>
            [RepositoryItemInfo("ebec5361-e876-4e66-a729-2e4e51576e03")]
            public virtual RepoItemInfo UnbenanntEditorInfo
            {
                get
                {
                    return _unbenannteditorInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("63d0e412-33ea-44fb-afab-d3e3f96f8be2")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("63d0e412-33ea-44fb-afab-d3e3f96f8be2")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

        /// <summary>
        /// The FrmUhrAppFolder folder.
        /// </summary>
        [RepositoryFolder("b2819dc5-6d4f-4c86-8077-0fdbced80579")]
        public partial class FrmUhrAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pbtimecontrolkommtInfo;
            RepoItemInfo _coluhrdtbeginnrow1Info;
            RepoItemInfo _rsbgtextaktzeitInfo;

            /// <summary>
            /// Creates a new FrmUhr  folder.
            /// </summary>
            public FrmUhrAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmUhr", "/form[@controlname='frmUhr']", parentFolder, 30000, null, true, "b2819dc5-6d4f-4c86-8077-0fdbced80579", "")
            {
                _pbtimecontrolkommtInfo = new RepoItemInfo(this, "PbTimecontrolKommt", "?/?/container[@controlname='TimecontrolKommtGroup']/button[@controlname='pbTimecontrol_Kommt']", "", 30000, null, "41dbc414-4033-4255-9894-2f55f6561ea9");
                _coluhrdtbeginnrow1Info = new RepoItemInfo(this, "ColUhrDtbeginnRow1", "container[@controlname='ClientArea']/container[@controlname='splitContainer1']/container[@controltypename='SplitterPanel' and @instance='0']/container[@controlname='tblAnwesend']/element[@controlname='mainGrid']/table[@accessiblename='FlexGrid']/row[@accessiblename='Row 1']/cell[@accessiblename='colUhr_dtbeginn Row 1']", "", 30000, null, "96b2e2dd-2cf9-4bf8-867d-855aa5461cf2");
                _rsbgtextaktzeitInfo = new RepoItemInfo(this, "RsBgTextAktZeit", "container[@controlname='ToolBar']/text[@controlname='rsBgTextAktZeit']", "", 30000, null, "7baa74cb-9f74-4de4-8261-66739e8e04f0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b2819dc5-6d4f-4c86-8077-0fdbced80579")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b2819dc5-6d4f-4c86-8077-0fdbced80579")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PbTimecontrolKommt item.
            /// </summary>
            [RepositoryItem("41dbc414-4033-4255-9894-2f55f6561ea9")]
            public virtual Ranorex.Button PbTimecontrolKommt
            {
                get
                {
                    return _pbtimecontrolkommtInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PbTimecontrolKommt item info.
            /// </summary>
            [RepositoryItemInfo("41dbc414-4033-4255-9894-2f55f6561ea9")]
            public virtual RepoItemInfo PbTimecontrolKommtInfo
            {
                get
                {
                    return _pbtimecontrolkommtInfo;
                }
            }

            /// <summary>
            /// The ColUhrDtbeginnRow1 item.
            /// </summary>
            [RepositoryItem("96b2e2dd-2cf9-4bf8-867d-855aa5461cf2")]
            public virtual Ranorex.Cell ColUhrDtbeginnRow1
            {
                get
                {
                    return _coluhrdtbeginnrow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColUhrDtbeginnRow1 item info.
            /// </summary>
            [RepositoryItemInfo("96b2e2dd-2cf9-4bf8-867d-855aa5461cf2")]
            public virtual RepoItemInfo ColUhrDtbeginnRow1Info
            {
                get
                {
                    return _coluhrdtbeginnrow1Info;
                }
            }

            /// <summary>
            /// The RsBgTextAktZeit item.
            /// </summary>
            [RepositoryItem("7baa74cb-9f74-4de4-8261-66739e8e04f0")]
            public virtual Ranorex.Text RsBgTextAktZeit
            {
                get
                {
                    return _rsbgtextaktzeitInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The RsBgTextAktZeit item info.
            /// </summary>
            [RepositoryItemInfo("7baa74cb-9f74-4de4-8261-66739e8e04f0")]
            public virtual RepoItemInfo RsBgTextAktZeitInfo
            {
                get
                {
                    return _rsbgtextaktzeitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
