///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace S_ART_003
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the S_ART_003Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("9891a735-2cc5-4706-8cea-885e4058a899")]
    public partial class S_ART_003Repository : RepoGenBaseFolder
    {
        static S_ART_003Repository instance = new S_ART_003Repository();
        S_ART_003RepositoryFolders.FrmArtAppFolder _frmart;
        S_ART_003RepositoryFolders.DlgMessageBoxAppFolder _dlgmessagebox;

        /// <summary>
        /// Gets the singleton class instance representing the S_ART_003Repository element repository.
        /// </summary>
        [RepositoryFolder("9891a735-2cc5-4706-8cea-885e4058a899")]
        public static S_ART_003Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public S_ART_003Repository() 
            : base("S_ART_003Repository", "/", null, 0, false, "9891a735-2cc5-4706-8cea-885e4058a899", ".\\RepositoryImages\\S_ART_003Repository9891a735.rximgres")
        {
            _frmart = new S_ART_003RepositoryFolders.FrmArtAppFolder(this);
            _dlgmessagebox = new S_ART_003RepositoryFolders.DlgMessageBoxAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9891a735-2cc5-4706-8cea-885e4058a899")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FrmArt folder.
        /// </summary>
        [RepositoryFolder("1cfc9a39-4295-43c9-8ddc-cad3e6993822")]
        public virtual S_ART_003RepositoryFolders.FrmArtAppFolder FrmArt
        {
            get { return _frmart; }
        }

        /// <summary>
        /// The DlgMessageBox folder.
        /// </summary>
        [RepositoryFolder("d6b3a652-bf9e-44fe-aad9-db4b8eb87bf5")]
        public virtual S_ART_003RepositoryFolders.DlgMessageBoxAppFolder DlgMessageBox
        {
            get { return _dlgmessagebox; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class S_ART_003RepositoryFolders
    {
        /// <summary>
        /// The FrmArtAppFolder folder.
        /// </summary>
        [RepositoryFolder("1cfc9a39-4295-43c9-8ddc-cad3e6993822")]
        public partial class FrmArtAppFolder : RepoGenBaseFolder
        {
            S_ART_003RepositoryFolders.PicTabsArtFolder _pictabsart;
            RepoItemInfo _titlebar100artikelstammverwaltenInfo;
            RepoItemInfo _suchleisteInfo;
            RepoItemInfo _zeile_suchleisteInfo;
            RepoItemInfo _art_nrInfo;
            RepoItemInfo _button_zurueckInfo;
            RepoItemInfo _button_newInfo;
            RepoItemInfo _button_nummerInfo;
            RepoItemInfo _bezeichnung1Info;
            RepoItemInfo _kurzbezInfo;
            RepoItemInfo _button_speichernInfo;
            RepoItemInfo _textkzInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _karteireiter_lagerInfo;
            RepoItemInfo _verwendung_chargeInfo;
            RepoItemInfo _folgeartikelInfo;
            RepoItemInfo _dfartnrInfo;

            /// <summary>
            /// Creates a new FrmArt  folder.
            /// </summary>
            public FrmArtAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmArt", "/form[@controlname='frmArt']", parentFolder, 30000, null, true, "1cfc9a39-4295-43c9-8ddc-cad3e6993822", "")
            {
                _pictabsart = new S_ART_003RepositoryFolders.PicTabsArtFolder(this);
                _titlebar100artikelstammverwaltenInfo = new RepoItemInfo(this, "TitleBar100ArtikelstammVerwalten", "titlebar[@accessiblerole='TitleBar']", "", 30000, null, "e86be035-ca20-4632-b448-63985fc27c23");
                _suchleisteInfo = new RepoItemInfo(this, "Suchleiste", "container[@controlname='searchContainer']/form[@controlname='frmSearchPage']/?/?/container[@controlname='SearchGroup1']//text[@accessiblerole='Text']", "", 30000, null, "64e332b4-1b2b-46e7-99fa-33d40661e075");
                _zeile_suchleisteInfo = new RepoItemInfo(this, "Zeile_Suchleiste", "container[@controlname='searchContainer']/form[@controlname='frmSearchPage']//table[@accessiblename='FlexGrid']/row[@accessiblename='Row 1']/cell[@accessiblename='Row 1 Column 0']", "", 30000, null, "e9ddf1b2-48c5-4f38-8b70-4ad4e043d90c");
                _art_nrInfo = new RepoItemInfo(this, "Art_Nr", "?/?/text[@controlname='dfArt_nr']", "", 30000, null, "a0790333-ddf2-4e7b-a4bc-5dca4c3e1c7f");
                _button_zurueckInfo = new RepoItemInfo(this, "Button_Zurueck", "container[@controlname='RibbonBar']/?/?/button[@controlname='pbNavigation_Back']", "", 30000, null, "48694598-e187-4789-81f8-9b9eafdf9589");
                _button_newInfo = new RepoItemInfo(this, "Button_NEW", "?/?/form[@controlname='frmSearchPage']/?/?/container[@controlname='SearchGroup2']/button[@controlname='pbNew']", "", 30000, null, "9bb9cd5a-4e70-48d6-92af-8636ce86db8f");
                _button_nummerInfo = new RepoItemInfo(this, "Button_Nummer", "?/?/container[@controlname='ExtrasGroup']/button[@controlname='pbExtras_Nummer']", "", 30000, null, "9d995061-3a39-45e6-a620-e249e8858a68");
                _bezeichnung1Info = new RepoItemInfo(this, "Bezeichnung1", "?/?/text[@controlname='dfArt_bez1']/text[@accessiblename='Bezeichnung-1']", "", 30000, null, "32b660ab-e523-4c7a-a1c5-0e0a3eb7e68b");
                _kurzbezInfo = new RepoItemInfo(this, "Kurzbez", "?/?/text[@controlname='dfArt_kbez']/text[@accessiblename='Kurzbez.']", "", 30000, null, "67e26fc2-62a7-4b10-b669-8439c6d41574");
                _button_speichernInfo = new RepoItemInfo(this, "Button_Speichern", "container[@controlname='RibbonBar']/?/?/button[@controlname='pbDataAccess_Save']", "", 30000, null, "1ac71760-c0f9-4cb9-9672-4a61a0cfc96e");
                _textkzInfo = new RepoItemInfo(this, "TextKz", "?/?/container[@controlname='groupBox16']/?/?/text[@accessiblename='Kz.']", "", 30000, null, "1e2ea2e2-7216-4f6a-b6e3-d4ca51775812");
                _textInfo = new RepoItemInfo(this, "Text", "?/?/container[@controlname='groupBox16']/text[@controlname='dfArt_nrfolge1']/text[@accessiblerole='Text']", "", 30000, null, "1a13fdd0-7ee4-4090-b4c8-3a3b6c71f13e");
                _karteireiter_lagerInfo = new RepoItemInfo(this, "Karteireiter_Lager", "?/?/tabpagelist[@controlname='picTabsArt']/tabpage[@accessiblename='&Lager']", "", 30000, null, "71d5dff4-071c-4d33-b133-7044290be208");
                _verwendung_chargeInfo = new RepoItemInfo(this, "Verwendung_Charge", "?/?/tabpagelist[@controlname='picTabsArt']/tabpage[@controlname='tpLager']//text[@accessiblename='Kalkulationsmodus']", "", 30000, null, "2b74301e-0051-43c8-9c85-394277a08d6e");
                _folgeartikelInfo = new RepoItemInfo(this, "Folgeartikel", "?/?/container[@controlname='groupBox16']", "", 30000, null, "e81fd8b2-982c-4cec-97c3-c7e7fb5831c6");
                _dfartnrInfo = new RepoItemInfo(this, "DfArtNr", "?/?/text[@controlname='dfArt_nr']", "", 30000, null, "e5310044-c0f9-4060-9436-ae2e2f708744");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1cfc9a39-4295-43c9-8ddc-cad3e6993822")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1cfc9a39-4295-43c9-8ddc-cad3e6993822")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar100ArtikelstammVerwalten item.
            /// </summary>
            [RepositoryItem("e86be035-ca20-4632-b448-63985fc27c23")]
            public virtual Ranorex.TitleBar TitleBar100ArtikelstammVerwalten
            {
                get
                {
                    return _titlebar100artikelstammverwaltenInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar100ArtikelstammVerwalten item info.
            /// </summary>
            [RepositoryItemInfo("e86be035-ca20-4632-b448-63985fc27c23")]
            public virtual RepoItemInfo TitleBar100ArtikelstammVerwaltenInfo
            {
                get
                {
                    return _titlebar100artikelstammverwaltenInfo;
                }
            }

            /// <summary>
            /// The Suchleiste item.
            /// </summary>
            [RepositoryItem("64e332b4-1b2b-46e7-99fa-33d40661e075")]
            public virtual Ranorex.Text Suchleiste
            {
                get
                {
                    return _suchleisteInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Suchleiste item info.
            /// </summary>
            [RepositoryItemInfo("64e332b4-1b2b-46e7-99fa-33d40661e075")]
            public virtual RepoItemInfo SuchleisteInfo
            {
                get
                {
                    return _suchleisteInfo;
                }
            }

            /// <summary>
            /// The Zeile_Suchleiste item.
            /// </summary>
            [RepositoryItem("e9ddf1b2-48c5-4f38-8b70-4ad4e043d90c")]
            public virtual Ranorex.Cell Zeile_Suchleiste
            {
                get
                {
                    return _zeile_suchleisteInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Zeile_Suchleiste item info.
            /// </summary>
            [RepositoryItemInfo("e9ddf1b2-48c5-4f38-8b70-4ad4e043d90c")]
            public virtual RepoItemInfo Zeile_SuchleisteInfo
            {
                get
                {
                    return _zeile_suchleisteInfo;
                }
            }

            /// <summary>
            /// The Art_Nr item.
            /// </summary>
            [RepositoryItem("a0790333-ddf2-4e7b-a4bc-5dca4c3e1c7f")]
            public virtual Ranorex.Text Art_Nr
            {
                get
                {
                    return _art_nrInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Art_Nr item info.
            /// </summary>
            [RepositoryItemInfo("a0790333-ddf2-4e7b-a4bc-5dca4c3e1c7f")]
            public virtual RepoItemInfo Art_NrInfo
            {
                get
                {
                    return _art_nrInfo;
                }
            }

            /// <summary>
            /// The Button_Zurueck item.
            /// </summary>
            [RepositoryItem("48694598-e187-4789-81f8-9b9eafdf9589")]
            public virtual Ranorex.Button Button_Zurueck
            {
                get
                {
                    return _button_zurueckInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_Zurueck item info.
            /// </summary>
            [RepositoryItemInfo("48694598-e187-4789-81f8-9b9eafdf9589")]
            public virtual RepoItemInfo Button_ZurueckInfo
            {
                get
                {
                    return _button_zurueckInfo;
                }
            }

            /// <summary>
            /// The Button_NEW item.
            /// </summary>
            [RepositoryItem("9bb9cd5a-4e70-48d6-92af-8636ce86db8f")]
            public virtual Ranorex.Button Button_NEW
            {
                get
                {
                    return _button_newInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_NEW item info.
            /// </summary>
            [RepositoryItemInfo("9bb9cd5a-4e70-48d6-92af-8636ce86db8f")]
            public virtual RepoItemInfo Button_NEWInfo
            {
                get
                {
                    return _button_newInfo;
                }
            }

            /// <summary>
            /// The Button_Nummer item.
            /// </summary>
            [RepositoryItem("9d995061-3a39-45e6-a620-e249e8858a68")]
            public virtual Ranorex.Button Button_Nummer
            {
                get
                {
                    return _button_nummerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_Nummer item info.
            /// </summary>
            [RepositoryItemInfo("9d995061-3a39-45e6-a620-e249e8858a68")]
            public virtual RepoItemInfo Button_NummerInfo
            {
                get
                {
                    return _button_nummerInfo;
                }
            }

            /// <summary>
            /// The Bezeichnung1 item.
            /// </summary>
            [RepositoryItem("32b660ab-e523-4c7a-a1c5-0e0a3eb7e68b")]
            public virtual Ranorex.Text Bezeichnung1
            {
                get
                {
                    return _bezeichnung1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Bezeichnung1 item info.
            /// </summary>
            [RepositoryItemInfo("32b660ab-e523-4c7a-a1c5-0e0a3eb7e68b")]
            public virtual RepoItemInfo Bezeichnung1Info
            {
                get
                {
                    return _bezeichnung1Info;
                }
            }

            /// <summary>
            /// The Kurzbez item.
            /// </summary>
            [RepositoryItem("67e26fc2-62a7-4b10-b669-8439c6d41574")]
            public virtual Ranorex.Text Kurzbez
            {
                get
                {
                    return _kurzbezInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Kurzbez item info.
            /// </summary>
            [RepositoryItemInfo("67e26fc2-62a7-4b10-b669-8439c6d41574")]
            public virtual RepoItemInfo KurzbezInfo
            {
                get
                {
                    return _kurzbezInfo;
                }
            }

            /// <summary>
            /// The Button_Speichern item.
            /// </summary>
            [RepositoryItem("1ac71760-c0f9-4cb9-9672-4a61a0cfc96e")]
            public virtual Ranorex.Button Button_Speichern
            {
                get
                {
                    return _button_speichernInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button_Speichern item info.
            /// </summary>
            [RepositoryItemInfo("1ac71760-c0f9-4cb9-9672-4a61a0cfc96e")]
            public virtual RepoItemInfo Button_SpeichernInfo
            {
                get
                {
                    return _button_speichernInfo;
                }
            }

            /// <summary>
            /// The TextKz item.
            /// </summary>
            [RepositoryItem("1e2ea2e2-7216-4f6a-b6e3-d4ca51775812")]
            public virtual Ranorex.Text TextKz
            {
                get
                {
                    return _textkzInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextKz item info.
            /// </summary>
            [RepositoryItemInfo("1e2ea2e2-7216-4f6a-b6e3-d4ca51775812")]
            public virtual RepoItemInfo TextKzInfo
            {
                get
                {
                    return _textkzInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("1a13fdd0-7ee4-4090-b4c8-3a3b6c71f13e")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("1a13fdd0-7ee4-4090-b4c8-3a3b6c71f13e")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Karteireiter_Lager item.
            /// </summary>
            [RepositoryItem("71d5dff4-071c-4d33-b133-7044290be208")]
            public virtual Ranorex.TabPage Karteireiter_Lager
            {
                get
                {
                    return _karteireiter_lagerInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Karteireiter_Lager item info.
            /// </summary>
            [RepositoryItemInfo("71d5dff4-071c-4d33-b133-7044290be208")]
            public virtual RepoItemInfo Karteireiter_LagerInfo
            {
                get
                {
                    return _karteireiter_lagerInfo;
                }
            }

            /// <summary>
            /// The Verwendung_Charge item.
            /// </summary>
            [RepositoryItem("2b74301e-0051-43c8-9c85-394277a08d6e")]
            public virtual Ranorex.Text Verwendung_Charge
            {
                get
                {
                    return _verwendung_chargeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Verwendung_Charge item info.
            /// </summary>
            [RepositoryItemInfo("2b74301e-0051-43c8-9c85-394277a08d6e")]
            public virtual RepoItemInfo Verwendung_ChargeInfo
            {
                get
                {
                    return _verwendung_chargeInfo;
                }
            }

            /// <summary>
            /// The Folgeartikel item.
            /// </summary>
            [RepositoryItem("e81fd8b2-982c-4cec-97c3-c7e7fb5831c6")]
            public virtual Ranorex.Container Folgeartikel
            {
                get
                {
                    return _folgeartikelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Folgeartikel item info.
            /// </summary>
            [RepositoryItemInfo("e81fd8b2-982c-4cec-97c3-c7e7fb5831c6")]
            public virtual RepoItemInfo FolgeartikelInfo
            {
                get
                {
                    return _folgeartikelInfo;
                }
            }

            /// <summary>
            /// The DfArtNr item.
            /// </summary>
            [RepositoryItem("e5310044-c0f9-4060-9436-ae2e2f708744")]
            public virtual Ranorex.Text DfArtNr
            {
                get
                {
                    return _dfartnrInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DfArtNr item info.
            /// </summary>
            [RepositoryItemInfo("e5310044-c0f9-4060-9436-ae2e2f708744")]
            public virtual RepoItemInfo DfArtNrInfo
            {
                get
                {
                    return _dfartnrInfo;
                }
            }

            /// <summary>
            /// The PicTabsArt folder.
            /// </summary>
            [RepositoryFolder("8a41ce59-616f-4abb-9145-145b801348e7")]
            public virtual S_ART_003RepositoryFolders.PicTabsArtFolder PicTabsArt
            {
                get { return _pictabsart; }
            }
        }

        /// <summary>
        /// The PicTabsArtFolder folder.
        /// </summary>
        [RepositoryFolder("8a41ce59-616f-4abb-9145-145b801348e7")]
        public partial class PicTabsArtFolder : RepoGenBaseFolder
        {
            RepoItemInfo _notizInfo;
            RepoItemInfo _lager_nrInfo;
            RepoItemInfo _erfassung_chargeInfo;
            RepoItemInfo _mindestbestandInfo;
            RepoItemInfo _notiz_textInfo;
            RepoItemInfo _lager_nr2Info;
            RepoItemInfo _tabelle_lagerInfo;

            /// <summary>
            /// Creates a new PicTabsArt  folder.
            /// </summary>
            public PicTabsArtFolder(RepoGenBaseFolder parentFolder) :
                    base("PicTabsArt", "?/?/tabpagelist[@controlname='picTabsArt']", parentFolder, 30000, null, false, "8a41ce59-616f-4abb-9145-145b801348e7", "")
            {
                _notizInfo = new RepoItemInfo(this, "Notiz", "tabpage[@accessiblename='N&otiz']", "", 30000, null, "62df41f7-9878-4446-b1bf-1395b6ed93f2");
                _lager_nrInfo = new RepoItemInfo(this, "Lager_Nr", "tabpage[@controlname='tpLager']//text[@controltypename='']", "", 30000, null, "6b844b55-d3c5-4a15-a6fc-b0a6e163eb04");
                _erfassung_chargeInfo = new RepoItemInfo(this, "Erfassung_Charge", "tabpage[@controlname='tpLager']/?/?/text[@controlname='dfArt_kzchargeerf']/text[@accessiblerole='Text']", "", 30000, null, "8acac338-ebcf-4d48-aed0-1332ba693332");
                _mindestbestandInfo = new RepoItemInfo(this, "Mindestbestand", "tabpage[@controlname='tpLager']/container[@controlname='tblArlg']/element[@controlname='mainGrid']/table[@accessiblename='FlexGrid']/?/?/cell[@accessiblename='colArlg_minbest Row 1']", "", 30000, null, "1007f76a-fb0f-4bf9-8186-abff0639eb5d");
                _notiz_textInfo = new RepoItemInfo(this, "Notiz_Text", "tabpage[@controlname='tpNotiz']//text[@accessiblerole='Text']", "", 30000, null, "7ce729bd-eed7-411d-a2e2-dd609c9f92bc");
                _lager_nr2Info = new RepoItemInfo(this, "Lager_nr2", "tabpage[@controlname='tpLager']/container[@controlname='tblArlg']/element[@controlname='mainGrid']/table[@accessiblename='FlexGrid']/?/?/cell[@accessiblename='colLag_nr Row 2']", "", 30000, null, "ad19c098-e7c7-42fd-9829-8dfdf87ebbbd");
                _tabelle_lagerInfo = new RepoItemInfo(this, "Tabelle_Lager", "tabpage[@controlname='tpLager']/container[@controlname='tblArlg']/element[@controlname='mainGrid']/table[@accessiblename='FlexGrid']", "", 30000, null, "4baf6734-aff4-4117-990f-2e0ab3cbd4a2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8a41ce59-616f-4abb-9145-145b801348e7")]
            public virtual Ranorex.TabPageList Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8a41ce59-616f-4abb-9145-145b801348e7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Notiz item.
            /// </summary>
            [RepositoryItem("62df41f7-9878-4446-b1bf-1395b6ed93f2")]
            public virtual Ranorex.TabPage Notiz
            {
                get
                {
                    return _notizInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Notiz item info.
            /// </summary>
            [RepositoryItemInfo("62df41f7-9878-4446-b1bf-1395b6ed93f2")]
            public virtual RepoItemInfo NotizInfo
            {
                get
                {
                    return _notizInfo;
                }
            }

            /// <summary>
            /// The Lager_Nr item.
            /// </summary>
            [RepositoryItem("6b844b55-d3c5-4a15-a6fc-b0a6e163eb04")]
            public virtual Ranorex.Text Lager_Nr
            {
                get
                {
                    return _lager_nrInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Lager_Nr item info.
            /// </summary>
            [RepositoryItemInfo("6b844b55-d3c5-4a15-a6fc-b0a6e163eb04")]
            public virtual RepoItemInfo Lager_NrInfo
            {
                get
                {
                    return _lager_nrInfo;
                }
            }

            /// <summary>
            /// The Erfassung_Charge item.
            /// </summary>
            [RepositoryItem("8acac338-ebcf-4d48-aed0-1332ba693332")]
            public virtual Ranorex.Text Erfassung_Charge
            {
                get
                {
                    return _erfassung_chargeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Erfassung_Charge item info.
            /// </summary>
            [RepositoryItemInfo("8acac338-ebcf-4d48-aed0-1332ba693332")]
            public virtual RepoItemInfo Erfassung_ChargeInfo
            {
                get
                {
                    return _erfassung_chargeInfo;
                }
            }

            /// <summary>
            /// The Mindestbestand item.
            /// </summary>
            [RepositoryItem("1007f76a-fb0f-4bf9-8186-abff0639eb5d")]
            public virtual Ranorex.Cell Mindestbestand
            {
                get
                {
                    return _mindestbestandInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Mindestbestand item info.
            /// </summary>
            [RepositoryItemInfo("1007f76a-fb0f-4bf9-8186-abff0639eb5d")]
            public virtual RepoItemInfo MindestbestandInfo
            {
                get
                {
                    return _mindestbestandInfo;
                }
            }

            /// <summary>
            /// The Notiz_Text item.
            /// </summary>
            [RepositoryItem("7ce729bd-eed7-411d-a2e2-dd609c9f92bc")]
            public virtual Ranorex.Text Notiz_Text
            {
                get
                {
                    return _notiz_textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Notiz_Text item info.
            /// </summary>
            [RepositoryItemInfo("7ce729bd-eed7-411d-a2e2-dd609c9f92bc")]
            public virtual RepoItemInfo Notiz_TextInfo
            {
                get
                {
                    return _notiz_textInfo;
                }
            }

            /// <summary>
            /// The Lager_nr2 item.
            /// </summary>
            [RepositoryItem("ad19c098-e7c7-42fd-9829-8dfdf87ebbbd")]
            public virtual Ranorex.Cell Lager_nr2
            {
                get
                {
                    return _lager_nr2Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Lager_nr2 item info.
            /// </summary>
            [RepositoryItemInfo("ad19c098-e7c7-42fd-9829-8dfdf87ebbbd")]
            public virtual RepoItemInfo Lager_nr2Info
            {
                get
                {
                    return _lager_nr2Info;
                }
            }

            /// <summary>
            /// The Tabelle_Lager item.
            /// </summary>
            [RepositoryItem("4baf6734-aff4-4117-990f-2e0ab3cbd4a2")]
            public virtual Ranorex.Table Tabelle_Lager
            {
                get
                {
                    return _tabelle_lagerInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Tabelle_Lager item info.
            /// </summary>
            [RepositoryItemInfo("4baf6734-aff4-4117-990f-2e0ab3cbd4a2")]
            public virtual RepoItemInfo Tabelle_LagerInfo
            {
                get
                {
                    return _tabelle_lagerInfo;
                }
            }
        }

        /// <summary>
        /// The DlgMessageBoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("d6b3a652-bf9e-44fe-aad9-db4b8eb87bf5")]
        public partial class DlgMessageBoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _meldungstextInfo;
            RepoItemInfo _button0Info;

            /// <summary>
            /// Creates a new DlgMessageBox  folder.
            /// </summary>
            public DlgMessageBoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DlgMessageBox", "/form[@controlname='dlgMessageBox']", parentFolder, 30000, null, true, "d6b3a652-bf9e-44fe-aad9-db4b8eb87bf5", "")
            {
                _meldungstextInfo = new RepoItemInfo(this, "Meldungstext", "text[@controlname='labelMeldungstext']", "", 30000, null, "5538162a-2a22-455a-8e2d-a41d8032561d");
                _button0Info = new RepoItemInfo(this, "Button0", "button[@controlname='button0']", "", 30000, null, "c60766c6-f645-468b-9570-0932ba5a73cf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d6b3a652-bf9e-44fe-aad9-db4b8eb87bf5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d6b3a652-bf9e-44fe-aad9-db4b8eb87bf5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Meldungstext item.
            /// </summary>
            [RepositoryItem("5538162a-2a22-455a-8e2d-a41d8032561d")]
            public virtual Ranorex.Text Meldungstext
            {
                get
                {
                    return _meldungstextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Meldungstext item info.
            /// </summary>
            [RepositoryItemInfo("5538162a-2a22-455a-8e2d-a41d8032561d")]
            public virtual RepoItemInfo MeldungstextInfo
            {
                get
                {
                    return _meldungstextInfo;
                }
            }

            /// <summary>
            /// The Button0 item.
            /// </summary>
            [RepositoryItem("c60766c6-f645-468b-9570-0932ba5a73cf")]
            public virtual Ranorex.Button Button0
            {
                get
                {
                    return _button0Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button0 item info.
            /// </summary>
            [RepositoryItemInfo("c60766c6-f645-468b-9570-0932ba5a73cf")]
            public virtual RepoItemInfo Button0Info
            {
                get
                {
                    return _button0Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
