///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace B_BUKA_007.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Nur_nummerische_Eingabe_Teil2 recording.
    /// </summary>
    [TestModule("bc0be029-ba7d-4ef1-b81a-bf14a4d036f9", ModuleType.Recording, 1)]
    public partial class Nur_nummerische_Eingabe_Teil2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::B_BUKA_007.B_BUKA_007Repository repository.
        /// </summary>
        public static global::B_BUKA_007.B_BUKA_007Repository repo = global::B_BUKA_007.B_BUKA_007Repository.Instance;

        static Nur_nummerische_Eingabe_Teil2 instance = new Nur_nummerische_Eingabe_Teil2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Nur_nummerische_Eingabe_Teil2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Nur_nummerische_Eingabe_Teil2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            // x
            Report.Log(ReportLevel.Info, "Set value", "x\r\nSetting attribute Text to '1000' on item 'TblBuka.ColBelegRow3_for_set_value'.", repo.TblBuka.ColBelegRow3_for_set_valueInfo, new RecordItemIndex(0));
            repo.TblBuka.ColBelegRow3_for_set_value.Element.SetAttributeValue("Text", "1000");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TblBuka.FlexGrid.ColTextRow3' at Center.", repo.TblBuka.FlexGrid.ColTextRow3Info, new RecordItemIndex(1));
            repo.TblBuka.FlexGrid.ColTextRow3.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Test_2' with focus on 'TblBuka.FlexGrid.ColTextRow3'.", repo.TblBuka.FlexGrid.ColTextRow3Info, new RecordItemIndex(2));
            repo.TblBuka.FlexGrid.ColTextRow3.PressKeys("Test_2");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TblBuka.FlexGrid.ColEingangRow3' at Center.", repo.TblBuka.FlexGrid.ColEingangRow3Info, new RecordItemIndex(3));
            repo.TblBuka.FlexGrid.ColEingangRow3.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '100' with focus on 'TblBuka.FlexGrid.ColEingangRow3'.", repo.TblBuka.FlexGrid.ColEingangRow3Info, new RecordItemIndex(4));
            repo.TblBuka.FlexGrid.ColEingangRow3.PressKeys("100");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TblBuka.PbDataAccessSave' at Center.", repo.TblBuka.PbDataAccessSaveInfo, new RecordItemIndex(5));
            repo.TblBuka.PbDataAccessSave.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1000') on item 'TblBuka.FlexGrid.ColBelegRow3'.", repo.TblBuka.FlexGrid.ColBelegRow3Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.TblBuka.FlexGrid.ColBelegRow3Info, "Text", "1000");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='5.200,00') on item 'TblBuka.FlexGrid.ColSaldoLfdRow3'.", repo.TblBuka.FlexGrid.ColSaldoLfdRow3Info, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.TblBuka.FlexGrid.ColSaldoLfdRow3Info, "Text", "5.200,00");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
