///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace X_MUSTER_004.Recordings_1
{
    public partial class Validierung_Variable_Monat_1_Feld_01_Usercode
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Validate_Periode_von(RepoItemInfo textInfo)
        {
            // Kommentar: Inhalt von Feld wird als Integer konvertiert
            // Fehler int periode_von_int = Convert.ToInt32(repo.frmVerbuch.dfPeriodeVon.TextValue);
            // Kommentar: Periode_von_int (konvertierte Inhalt von Feld als integer) wird als String konvertiert
            //Fehler string periode_von_string = Periode_von_int.ToString();
            
            //Fehler: Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (ControlText=$Monat_1) on item 'textInfo'.", textInfo);
            // Kommentart Vergleichen die Periode_string (konvertierte Inhalt von Feld als integer) und Variable Monat_1
            //Fehler: Validate.AreEqual(periode_von_string, Monat_1);
}


        public void Validate_Periode_bis(RepoItemInfo textInfo)
        {
                 // Inhalt von Feld wird als Integer konvertiert
            int Monat_1_int = Convert.ToInt32 (Monat_1);
            // Prüfen ob Periode zwei Stellen hat
            if(Monat_1_int<9)
                // Wenn Periode kleiner als 9 ist: 0 voranstellen
                Validate.AttributeEqual(textInfo, "Text", '0'+Monat_1);
            else
                Validate.AttributeEqual(textInfo, "Text", Monat_1);

        }

    }
}
