///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace B_KLBL_Schnelltest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the B_KLBL_SchnelltestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2149adad-26be-48ab-b368-c7dfb413c2a1")]
    public partial class B_KLBL_SchnelltestRepository : RepoGenBaseFolder
    {
        static B_KLBL_SchnelltestRepository instance = new B_KLBL_SchnelltestRepository();
        B_KLBL_SchnelltestRepositoryFolders.FrmKlBlAppFolder _frmklbl;

        /// <summary>
        /// Gets the singleton class instance representing the B_KLBL_SchnelltestRepository element repository.
        /// </summary>
        [RepositoryFolder("2149adad-26be-48ab-b368-c7dfb413c2a1")]
        public static B_KLBL_SchnelltestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public B_KLBL_SchnelltestRepository() 
            : base("B_KLBL_SchnelltestRepository", "/", null, 0, false, "2149adad-26be-48ab-b368-c7dfb413c2a1", ".\\RepositoryImages\\B_KLBL_SchnelltestRepository2149adad.rximgres")
        {
            _frmklbl = new B_KLBL_SchnelltestRepositoryFolders.FrmKlBlAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2149adad-26be-48ab-b368-c7dfb413c2a1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FrmKlBl folder.
        /// </summary>
        [RepositoryFolder("d6677c81-9569-4432-ae28-554de87d769e")]
        public virtual B_KLBL_SchnelltestRepositoryFolders.FrmKlBlAppFolder FrmKlBl
        {
            get { return _frmklbl; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class B_KLBL_SchnelltestRepositoryFolders
    {
        /// <summary>
        /// The FrmKlBlAppFolder folder.
        /// </summary>
        [RepositoryFolder("d6677c81-9569-4432-ae28-554de87d769e")]
        public partial class FrmKlBlAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titlebar100kontoblattlieferantenInfo;

            /// <summary>
            /// Creates a new FrmKlBl  folder.
            /// </summary>
            public FrmKlBlAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmKlBl", "/form[@controlname='frmKlBl']", parentFolder, 30000, null, true, "d6677c81-9569-4432-ae28-554de87d769e", "")
            {
                _titlebar100kontoblattlieferantenInfo = new RepoItemInfo(this, "TitleBar100KontoblattLieferanten", "titlebar[@accessiblerole='TitleBar']", "", 30000, null, "983af920-a265-434d-9459-a149e58b8e60");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d6677c81-9569-4432-ae28-554de87d769e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d6677c81-9569-4432-ae28-554de87d769e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar100KontoblattLieferanten item.
            /// </summary>
            [RepositoryItem("983af920-a265-434d-9459-a149e58b8e60")]
            public virtual Ranorex.TitleBar TitleBar100KontoblattLieferanten
            {
                get
                {
                    return _titlebar100kontoblattlieferantenInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar100KontoblattLieferanten item info.
            /// </summary>
            [RepositoryItemInfo("983af920-a265-434d-9459-a149e58b8e60")]
            public virtual RepoItemInfo TitleBar100KontoblattLieferantenInfo
            {
                get
                {
                    return _titlebar100kontoblattlieferantenInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
