///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace L_DISP_001.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BV_mit_Optionen recording.
    /// </summary>
    [TestModule("20f34b89-656b-4b5e-b042-bae30379d3f9", ModuleType.Recording, 1)]
    public partial class BV_mit_Optionen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::L_DISP_001.L_DISP_001Repository repository.
        /// </summary>
        public static global::L_DISP_001.L_DISP_001Repository repo = global::L_DISP_001.L_DISP_001Repository.Instance;

        static BV_mit_Optionen instance = new BV_mit_Optionen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BV_mit_Optionen()
        {
            Lager = "100";
            Artikel1 = "100020";
            Artikel2 = "100021";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BV_mit_Optionen Instance
        {
            get { return instance; }
        }

#region Variables

        string _Lager;

        /// <summary>
        /// Gets or sets the value of variable Lager.
        /// </summary>
        [TestVariable("dcbd7687-dc16-4ba4-819e-d8942dc00531")]
        public string Lager
        {
            get { return _Lager; }
            set { _Lager = value; }
        }

        string _Artikel1;

        /// <summary>
        /// Gets or sets the value of variable Artikel1.
        /// </summary>
        [TestVariable("e941c663-7864-42f5-bf01-f0a01ac1bdb4")]
        public string Artikel1
        {
            get { return _Artikel1; }
            set { _Artikel1 = value; }
        }

        string _Artikel2;

        /// <summary>
        /// Gets or sets the value of variable Artikel2.
        /// </summary>
        [TestVariable("b26e64b8-f50b-463b-b93b-0f8f963d1297")]
        public string Artikel2
        {
            get { return _Artikel2; }
            set { _Artikel2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'FrmDispo.RbBsvkMindest'.", repo.FrmDispo.RbBsvkMindestInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.FrmDispo.RbBsvkMindestInfo, "Checked", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Checked='True') on item 'FrmDispo.CbBsvkBestand'.", repo.FrmDispo.CbBsvkBestandInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.FrmDispo.CbBsvkBestandInfo, "Checked", "True");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Lager) on item 'FrmDispo.Lager'.", repo.FrmDispo.LagerInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.FrmDispo.LagerInfo, "Text", Lager);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Artikel1) on item 'FrmDispo.ColWert1Row4'.", repo.FrmDispo.ColWert1Row4Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.FrmDispo.ColWert1Row4Info, "Text", Artikel1);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='100024') on item 'FrmDispo.ColWert2Row4'.", repo.FrmDispo.ColWert2Row4Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.FrmDispo.ColWert2Row4Info, "Text", "100024");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmDispo.RbBsvkZentral' at Center.", repo.FrmDispo.RbBsvkZentralInfo, new RecordItemIndex(5));
            repo.FrmDispo.RbBsvkZentral.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmDispo.PbExtrasListe' at Center.", repo.FrmDispo.PbExtrasListeInfo, new RecordItemIndex(6));
            repo.FrmDispo.PbExtrasListe.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'TblDispVSL.ColArtNrRow2'.", repo.TblDispVSL.ColArtNrRow2Info, new RecordItemIndex(7));
            Validate.NotExists(repo.TblDispVSL.ColArtNrRow2Info);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TblDispVSL.Schliessen' at Center.", repo.TblDispVSL.SchliessenInfo, new RecordItemIndex(8));
            repo.TblDispVSL.Schliessen.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmDispo.CbBsvkNormal' at Center.", repo.FrmDispo.CbBsvkNormalInfo, new RecordItemIndex(9));
            repo.FrmDispo.CbBsvkNormal.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmDispo.RbDezentral' at Center.", repo.FrmDispo.RbDezentralInfo, new RecordItemIndex(10));
            repo.FrmDispo.RbDezentral.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmDispo.PbExtrasListe' at Center.", repo.FrmDispo.PbExtrasListeInfo, new RecordItemIndex(11));
            repo.FrmDispo.PbExtrasListe.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Artikel1) on item 'TblDispVSL.ColArtNrRow1'.", repo.TblDispVSL.ColArtNrRow1Info, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.TblDispVSL.ColArtNrRow1Info, "Text", Artikel1);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Artikel2) on item 'TblDispVSL.ColArtNrRow2'.", repo.TblDispVSL.ColArtNrRow2Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.TblDispVSL.ColArtNrRow2Info, "Text", Artikel2);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2') on item 'TblDispVSL.ColMengeOffenRow1'.", repo.TblDispVSL.ColMengeOffenRow1Info, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.TblDispVSL.ColMengeOffenRow1Info, "Text", "2");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='3') on item 'TblDispVSL.ColMengeOffenRow2'.", repo.TblDispVSL.ColMengeOffenRow2Info, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.TblDispVSL.ColMengeOffenRow2Info, "Text", "3");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
