///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace B_UVA_002.Recordings_Formular_Werte_2017_1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UVA_2017_1_Tabelle_pruefen recording.
    /// </summary>
    [TestModule("362d9797-bd29-447f-9536-1a9460033c31", ModuleType.Recording, 1)]
    public partial class UVA_2017_1_Tabelle_pruefen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::B_UVA_002.B_UVA_002Repository repository.
        /// </summary>
        public static global::B_UVA_002.B_UVA_002Repository repo = global::B_UVA_002.B_UVA_002Repository.Instance;

        static UVA_2017_1_Tabelle_pruefen instance = new UVA_2017_1_Tabelle_pruefen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UVA_2017_1_Tabelle_pruefen()
        {
            Tabelle_Werte_A20_2_2017_1 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UVA_2017_1_Tabelle_pruefen Instance
        {
            get { return instance; }
        }

#region Variables

        string _Tabelle_Werte_A20_2_2017_1;

        /// <summary>
        /// Gets or sets the value of variable Tabelle_Werte_A20_2_2017_1.
        /// </summary>
        [TestVariable("2ad128d1-8396-4421-9a22-83737a5268ec")]
        public string Tabelle_Werte_A20_2_2017_1
        {
            get { return _Tabelle_Werte_A20_2_2017_1; }
            set { _Tabelle_Werte_A20_2_2017_1 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$Tabelle_Werte_A20_2_2017_1) on item 'TblDrucken.Row1'.", repo.TblDrucken.Row1Info, new RecordItemIndex(0));
            Validate.AttributeContains(repo.TblDrucken.Row1Info, "Text", Tabelle_Werte_A20_2_2017_1);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
