///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace B_BUKA_004
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the B_BUKA_004Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("d0a85d1e-1bdb-4009-b0d7-4877669d3f41")]
    public partial class B_BUKA_004Repository : RepoGenBaseFolder
    {
        static B_BUKA_004Repository instance = new B_BUKA_004Repository();
        B_BUKA_004RepositoryFolders.TblBukaAppFolder _tblbuka;
        B_BUKA_004RepositoryFolders.BBUKAAppFolder _bbuka;
        B_BUKA_004RepositoryFolders.DlgMessageBoxAppFolder _dlgmessagebox;

        /// <summary>
        /// Gets the singleton class instance representing the B_BUKA_004Repository element repository.
        /// </summary>
        [RepositoryFolder("d0a85d1e-1bdb-4009-b0d7-4877669d3f41")]
        public static B_BUKA_004Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public B_BUKA_004Repository() 
            : base("B_BUKA_004Repository", "/", null, 0, false, "d0a85d1e-1bdb-4009-b0d7-4877669d3f41", ".\\RepositoryImages\\B_BUKA_004Repositoryd0a85d1e.rximgres")
        {
            _tblbuka = new B_BUKA_004RepositoryFolders.TblBukaAppFolder(this);
            _bbuka = new B_BUKA_004RepositoryFolders.BBUKAAppFolder(this);
            _dlgmessagebox = new B_BUKA_004RepositoryFolders.DlgMessageBoxAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d0a85d1e-1bdb-4009-b0d7-4877669d3f41")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The TblBuka folder.
        /// </summary>
        [RepositoryFolder("c0d90598-895c-4c6f-9f39-9c7d67028d83")]
        public virtual B_BUKA_004RepositoryFolders.TblBukaAppFolder TblBuka
        {
            get { return _tblbuka; }
        }

        /// <summary>
        /// The BBUKA folder.
        /// </summary>
        [RepositoryFolder("c33ea8f1-8c56-410b-b0e3-e45403c20370")]
        public virtual B_BUKA_004RepositoryFolders.BBUKAAppFolder BBUKA
        {
            get { return _bbuka; }
        }

        /// <summary>
        /// The DlgMessageBox folder.
        /// </summary>
        [RepositoryFolder("ef7ffc8a-b7c9-4b2c-b929-009bcccd4558")]
        public virtual B_BUKA_004RepositoryFolders.DlgMessageBoxAppFolder DlgMessageBox
        {
            get { return _dlgmessagebox; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class B_BUKA_004RepositoryFolders
    {
        /// <summary>
        /// The TblBukaAppFolder folder.
        /// </summary>
        [RepositoryFolder("c0d90598-895c-4c6f-9f39-9c7d67028d83")]
        public partial class TblBukaAppFolder : RepoGenBaseFolder
        {
            B_BUKA_004RepositoryFolders.ToolBarFolder _toolbar;
            B_BUKA_004RepositoryFolders.FlexGrid1Folder _flexgrid1;
            RepoItemInfo _titlebar100kassabuchInfo;
            RepoItemInfo _pbdataaccessnewInfo;
            RepoItemInfo _pbdataaccessloadInfo;
            RepoItemInfo _pbdataaccesssaveInfo;
            RepoItemInfo _pbtoolbaritemssplittungInfo;
            RepoItemInfo _pbstandard1pruefenInfo;
            RepoItemInfo _pagerightInfo;

            /// <summary>
            /// Creates a new TblBuka  folder.
            /// </summary>
            public TblBukaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TblBuka", "/form[@controlname='tblBuka']", parentFolder, 30000, null, true, "c0d90598-895c-4c6f-9f39-9c7d67028d83", "")
            {
                _toolbar = new B_BUKA_004RepositoryFolders.ToolBarFolder(this);
                _flexgrid1 = new B_BUKA_004RepositoryFolders.FlexGrid1Folder(this);
                _titlebar100kassabuchInfo = new RepoItemInfo(this, "TitleBar100Kassabuch", "titlebar[@accessiblerole='TitleBar']", "", 30000, null, "8143f463-18bb-4a55-b5f9-a01af84b8564");
                _pbdataaccessnewInfo = new RepoItemInfo(this, "PbDataAccessNew", "container[@controlname='RibbonBar']/container[@controlname='DataAccessGroup']/button[@controlname='pbDataAccess_New']", "", 30000, null, "d4f5abd7-903c-4613-a78a-c6912868c37d");
                _pbdataaccessloadInfo = new RepoItemInfo(this, "PbDataAccessLoad", "container[@controlname='RibbonBar']/container[@controlname='DataAccessGroup']/button[@controlname='pbDataAccess_Load']", "", 30000, null, "d89e2569-9a3a-4920-8d9f-71b63336169d");
                _pbdataaccesssaveInfo = new RepoItemInfo(this, "PbDataAccessSave", "container[@controlname='RibbonBar']/container[@controlname='DataAccessGroup']/button[@controlname='pbDataAccess_Save']", "", 30000, null, "7701f1ce-2cb1-403a-8ddf-12ba655ebb76");
                _pbtoolbaritemssplittungInfo = new RepoItemInfo(this, "PbToolBarItemsSplittung", "container[@controlname='RibbonBar']/container[@controlname='ToolBarItemsGroup']/button[@controlname='pbToolBarItems_Splittung']", "", 30000, null, "bb943f6a-b926-4206-9bfa-e06847e59af4");
                _pbstandard1pruefenInfo = new RepoItemInfo(this, "PbStandard1Pruefen", "container[@controlname='RibbonBar']/container[@controlname='CommonGroup']/button[@controlname='pbStandard1']", "", 30000, null, "040c7f7d-7665-40b6-b964-fbe7f391e6d4");
                _pagerightInfo = new RepoItemInfo(this, "PageRight", "container[@controlname='ChildTableWindow']/element[@controlname='splitGrid']/scrollbar[@style='Horizontal']/button[@text='PageRight']", "", 30000, null, "2d221cb2-5e86-46a2-9fc5-a6e4a00a785d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c0d90598-895c-4c6f-9f39-9c7d67028d83")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c0d90598-895c-4c6f-9f39-9c7d67028d83")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar100Kassabuch item.
            /// </summary>
            [RepositoryItem("8143f463-18bb-4a55-b5f9-a01af84b8564")]
            public virtual Ranorex.TitleBar TitleBar100Kassabuch
            {
                get
                {
                    return _titlebar100kassabuchInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar100Kassabuch item info.
            /// </summary>
            [RepositoryItemInfo("8143f463-18bb-4a55-b5f9-a01af84b8564")]
            public virtual RepoItemInfo TitleBar100KassabuchInfo
            {
                get
                {
                    return _titlebar100kassabuchInfo;
                }
            }

            /// <summary>
            /// The PbDataAccessNew item.
            /// </summary>
            [RepositoryItem("d4f5abd7-903c-4613-a78a-c6912868c37d")]
            public virtual Ranorex.Button PbDataAccessNew
            {
                get
                {
                    return _pbdataaccessnewInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PbDataAccessNew item info.
            /// </summary>
            [RepositoryItemInfo("d4f5abd7-903c-4613-a78a-c6912868c37d")]
            public virtual RepoItemInfo PbDataAccessNewInfo
            {
                get
                {
                    return _pbdataaccessnewInfo;
                }
            }

            /// <summary>
            /// The PbDataAccessLoad item.
            /// </summary>
            [RepositoryItem("d89e2569-9a3a-4920-8d9f-71b63336169d")]
            public virtual Ranorex.Button PbDataAccessLoad
            {
                get
                {
                    return _pbdataaccessloadInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PbDataAccessLoad item info.
            /// </summary>
            [RepositoryItemInfo("d89e2569-9a3a-4920-8d9f-71b63336169d")]
            public virtual RepoItemInfo PbDataAccessLoadInfo
            {
                get
                {
                    return _pbdataaccessloadInfo;
                }
            }

            /// <summary>
            /// The PbDataAccessSave item.
            /// </summary>
            [RepositoryItem("7701f1ce-2cb1-403a-8ddf-12ba655ebb76")]
            public virtual Ranorex.Button PbDataAccessSave
            {
                get
                {
                    return _pbdataaccesssaveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PbDataAccessSave item info.
            /// </summary>
            [RepositoryItemInfo("7701f1ce-2cb1-403a-8ddf-12ba655ebb76")]
            public virtual RepoItemInfo PbDataAccessSaveInfo
            {
                get
                {
                    return _pbdataaccesssaveInfo;
                }
            }

            /// <summary>
            /// The PbToolBarItemsSplittung item.
            /// </summary>
            [RepositoryItem("bb943f6a-b926-4206-9bfa-e06847e59af4")]
            public virtual Ranorex.Button PbToolBarItemsSplittung
            {
                get
                {
                    return _pbtoolbaritemssplittungInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PbToolBarItemsSplittung item info.
            /// </summary>
            [RepositoryItemInfo("bb943f6a-b926-4206-9bfa-e06847e59af4")]
            public virtual RepoItemInfo PbToolBarItemsSplittungInfo
            {
                get
                {
                    return _pbtoolbaritemssplittungInfo;
                }
            }

            /// <summary>
            /// The PbStandard1Pruefen item.
            /// </summary>
            [RepositoryItem("040c7f7d-7665-40b6-b964-fbe7f391e6d4")]
            public virtual Ranorex.Button PbStandard1Pruefen
            {
                get
                {
                    return _pbstandard1pruefenInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PbStandard1Pruefen item info.
            /// </summary>
            [RepositoryItemInfo("040c7f7d-7665-40b6-b964-fbe7f391e6d4")]
            public virtual RepoItemInfo PbStandard1PruefenInfo
            {
                get
                {
                    return _pbstandard1pruefenInfo;
                }
            }

            /// <summary>
            /// The PageRight item.
            /// </summary>
            [RepositoryItem("2d221cb2-5e86-46a2-9fc5-a6e4a00a785d")]
            public virtual Ranorex.Button PageRight
            {
                get
                {
                    return _pagerightInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PageRight item info.
            /// </summary>
            [RepositoryItemInfo("2d221cb2-5e86-46a2-9fc5-a6e4a00a785d")]
            public virtual RepoItemInfo PageRightInfo
            {
                get
                {
                    return _pagerightInfo;
                }
            }

            /// <summary>
            /// The ToolBar folder.
            /// </summary>
            [RepositoryFolder("6550c921-4ce4-40a2-99d4-15c1cfd3baca")]
            public virtual B_BUKA_004RepositoryFolders.ToolBarFolder ToolBar
            {
                get { return _toolbar; }
            }

            /// <summary>
            /// The FlexGrid1 folder.
            /// </summary>
            [RepositoryFolder("91b48de0-3fb7-4c42-b2a7-c661355eaaaf")]
            public virtual B_BUKA_004RepositoryFolders.FlexGrid1Folder FlexGrid1
            {
                get { return _flexgrid1; }
            }
        }

        /// <summary>
        /// The ToolBarFolder folder.
        /// </summary>
        [RepositoryFolder("6550c921-4ce4-40a2-99d4-15c1cfd3baca")]
        public partial class ToolBarFolder : RepoGenBaseFolder
        {
            RepoItemInfo _zahlkontoInfo;
            RepoItemInfo _dfdatumvonInfo;
            RepoItemInfo _dfdatumbisInfo;
            RepoItemInfo _cbklInfo;
            RepoItemInfo _cbanzeigebereicheInfo;

            /// <summary>
            /// Creates a new ToolBar  folder.
            /// </summary>
            public ToolBarFolder(RepoGenBaseFolder parentFolder) :
                    base("ToolBar", "container[@controlname='ToolBar']", parentFolder, 30000, null, false, "6550c921-4ce4-40a2-99d4-15c1cfd3baca", "")
            {
                _zahlkontoInfo = new RepoItemInfo(this, "Zahlkonto", "container[@controlname='frame1']/text[@controlname='dfKto_nr']/text[@accessiblename='Zahlkonto']", "", 30000, null, "d9153f33-8935-43f4-9ed2-ede306af1466");
                _dfdatumvonInfo = new RepoItemInfo(this, "DfDatumVon", "container[@controlname='frame1']/text[@controlname='dfDatum_von']/text[@accessiblename='Datum von']", "", 30000, null, "00aadb4a-6812-4e3b-912a-75bb40bcf64a");
                _dfdatumbisInfo = new RepoItemInfo(this, "DfDatumBis", "container[@controlname='frame1']/text[@controlname='dfDatum_bis']/text[@accessiblename='bis']", "", 30000, null, "f65d0dee-fe10-4bd2-a10c-0f2e3c009f54");
                _cbklInfo = new RepoItemInfo(this, "CbKL", "container[@controlname='frame1']/container[@controlname='groupBox1']/checkbox[@controlname='cbKL']", "", 30000, null, "c8fb8e71-a5a9-453c-88bb-847ca19fa274");
                _cbanzeigebereicheInfo = new RepoItemInfo(this, "CbAnzeigeBereiche", "container[@controlname='frame1']/container[@controlname='groupBox1']/checkbox[@controlname='cbAnzeige_Bereiche']", "", 30000, null, "35204d66-97cf-4d39-919e-6e84ea0bd802");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6550c921-4ce4-40a2-99d4-15c1cfd3baca")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6550c921-4ce4-40a2-99d4-15c1cfd3baca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Zahlkonto item.
            /// </summary>
            [RepositoryItem("d9153f33-8935-43f4-9ed2-ede306af1466")]
            public virtual Ranorex.Text Zahlkonto
            {
                get
                {
                    return _zahlkontoInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Zahlkonto item info.
            /// </summary>
            [RepositoryItemInfo("d9153f33-8935-43f4-9ed2-ede306af1466")]
            public virtual RepoItemInfo ZahlkontoInfo
            {
                get
                {
                    return _zahlkontoInfo;
                }
            }

            /// <summary>
            /// The DfDatumVon item.
            /// </summary>
            [RepositoryItem("00aadb4a-6812-4e3b-912a-75bb40bcf64a")]
            public virtual Ranorex.Text DfDatumVon
            {
                get
                {
                    return _dfdatumvonInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DfDatumVon item info.
            /// </summary>
            [RepositoryItemInfo("00aadb4a-6812-4e3b-912a-75bb40bcf64a")]
            public virtual RepoItemInfo DfDatumVonInfo
            {
                get
                {
                    return _dfdatumvonInfo;
                }
            }

            /// <summary>
            /// The DfDatumBis item.
            /// </summary>
            [RepositoryItem("f65d0dee-fe10-4bd2-a10c-0f2e3c009f54")]
            public virtual Ranorex.Text DfDatumBis
            {
                get
                {
                    return _dfdatumbisInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DfDatumBis item info.
            /// </summary>
            [RepositoryItemInfo("f65d0dee-fe10-4bd2-a10c-0f2e3c009f54")]
            public virtual RepoItemInfo DfDatumBisInfo
            {
                get
                {
                    return _dfdatumbisInfo;
                }
            }

            /// <summary>
            /// The CbKL item.
            /// </summary>
            [RepositoryItem("c8fb8e71-a5a9-453c-88bb-847ca19fa274")]
            public virtual Ranorex.CheckBox CbKL
            {
                get
                {
                    return _cbklInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CbKL item info.
            /// </summary>
            [RepositoryItemInfo("c8fb8e71-a5a9-453c-88bb-847ca19fa274")]
            public virtual RepoItemInfo CbKLInfo
            {
                get
                {
                    return _cbklInfo;
                }
            }

            /// <summary>
            /// The CbAnzeigeBereiche item.
            /// </summary>
            [RepositoryItem("35204d66-97cf-4d39-919e-6e84ea0bd802")]
            public virtual Ranorex.CheckBox CbAnzeigeBereiche
            {
                get
                {
                    return _cbanzeigebereicheInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CbAnzeigeBereiche item info.
            /// </summary>
            [RepositoryItemInfo("35204d66-97cf-4d39-919e-6e84ea0bd802")]
            public virtual RepoItemInfo CbAnzeigeBereicheInfo
            {
                get
                {
                    return _cbanzeigebereicheInfo;
                }
            }
        }

        /// <summary>
        /// The FlexGrid1Folder folder.
        /// </summary>
        [RepositoryFolder("91b48de0-3fb7-4c42-b2a7-c661355eaaaf")]
        public partial class FlexGrid1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _flexgridInfo;
            RepoItemInfo _colbukaklrow0_spaltenueberschriftInfo;
            RepoItemInfo _coltextrow1Info;
            RepoItemInfo _row3column0Info;
            RepoItemInfo _coltagrow3Info;
            RepoItemInfo _colposrow3Info;
            RepoItemInfo _coltextrow3Info;
            RepoItemInfo _colausgangrow3Info;
            RepoItemInfo _colbektnr1row3Info;
            RepoItemInfo _colktonrrow3Info;
            RepoItemInfo _colsaldolfdrow3Info;
            RepoItemInfo _row4column0Info;
            RepoItemInfo _colausgangrow4Info;
            RepoItemInfo _colustcoderow4Info;
            RepoItemInfo _colktonrrow4Info;
            RepoItemInfo _colbektnr1row4Info;
            RepoItemInfo _coltagrow4Info;
            RepoItemInfo _colbelegrow4Info;
            RepoItemInfo _colposrow4Info;
            RepoItemInfo _coltextrow4Info;
            RepoItemInfo _colsaldolfdrow4Info;
            RepoItemInfo _row5column0Info;
            RepoItemInfo _coltagrow5Info;
            RepoItemInfo _colbelegrow5Info;
            RepoItemInfo _colposrow5Info;
            RepoItemInfo _coltextrow5Info;
            RepoItemInfo _coleingangrow5Info;
            RepoItemInfo _colausgangrow5Info;
            RepoItemInfo _colktonrrow5Info;
            RepoItemInfo _colbektnr1row5Info;
            RepoItemInfo _colsaldolfdrow5Info;
            RepoItemInfo _colfehlerrow5Info;
            RepoItemInfo _row6column0Info;
            RepoItemInfo _colausgangrow6Info;
            RepoItemInfo _coltagrow6Info;
            RepoItemInfo _colbelegrow6Info;
            RepoItemInfo _colposrow6Info;
            RepoItemInfo _coltextrow6Info;
            RepoItemInfo _colktonrrow6Info;
            RepoItemInfo _colustbetragrow6Info;
            RepoItemInfo _colbektnr1row6Info;
            RepoItemInfo _colsaldolfdrow6Info;
            RepoItemInfo _colausgangrow7Info;
            RepoItemInfo _coltagrow7Info;
            RepoItemInfo _colbelegrow7Info;
            RepoItemInfo _colposrow7Info;
            RepoItemInfo _coltextrow7Info;
            RepoItemInfo _colsaldolfdrow7Info;
            RepoItemInfo _colbektnr1row7Info;
            RepoItemInfo _colktonrrow7Info;
            RepoItemInfo _coltagrow8Info;
            RepoItemInfo _colbelegrow8Info;
            RepoItemInfo _colposrow8Info;
            RepoItemInfo _coltextrow8Info;
            RepoItemInfo _colausgangrow8Info;
            RepoItemInfo _colsaldolfdrow8Info;
            RepoItemInfo _colktonrrow8Info;
            RepoItemInfo _colbektnr1row8Info;
            RepoItemInfo _colustcoderow5Info;

            /// <summary>
            /// Creates a new FlexGrid1  folder.
            /// </summary>
            public FlexGrid1Folder(RepoGenBaseFolder parentFolder) :
                    base("FlexGrid1", "container[@controlname='ChildTableWindow']/element[@controlname='mainGrid']/table[@accessiblename='FlexGrid']", parentFolder, 30000, null, false, "91b48de0-3fb7-4c42-b2a7-c661355eaaaf", "")
            {
                _flexgridInfo = new RepoItemInfo(this, "FlexGrid", "", "", 30000, null, "a392e9b9-43c5-41f8-805e-17732e9fb1b2");
                _colbukaklrow0_spaltenueberschriftInfo = new RepoItemInfo(this, "ColBukaKlRow0_Spaltenueberschrift", "row[@accessiblename='Row 0']/cell[@accessiblename='colBuka_kl Row 0']", "", 30000, null, "d4dbbd0a-4d6a-4cce-9a58-a3526591e613");
                _coltextrow1Info = new RepoItemInfo(this, "ColTextRow1", "row[@accessiblename='Row 1']/cell[@accessiblename='colText Row 1']", "", 30000, null, "46ea5ab6-d92c-4767-b347-dddecb9ced4b");
                _row3column0Info = new RepoItemInfo(this, "Row3Column0", "row[@accessiblename='Row 3']/cell[@accessiblename='Row 3 Column 0']", "", 30000, null, "8fd81c39-928d-4a40-bb91-369094cf488a");
                _coltagrow3Info = new RepoItemInfo(this, "ColTagRow3", "row[@accessiblename='Row 3']/cell[@accessiblename='colTag Row 3']", "", 30000, null, "6dae7a08-c29e-4e06-8f9f-2ca57abfb9da");
                _colposrow3Info = new RepoItemInfo(this, "ColPosRow3", "row[@accessiblename='Row 3']/cell[@accessiblename='colPos Row 3']", "", 30000, null, "e70f00b5-6532-4158-b5e7-0fb3c0ff9ab9");
                _coltextrow3Info = new RepoItemInfo(this, "ColTextRow3", "row[@accessiblename='Row 3']/cell[@accessiblename='colText Row 3']", "", 30000, null, "b8ff2686-d69c-4550-b740-50a620bc359d");
                _colausgangrow3Info = new RepoItemInfo(this, "ColAusgangRow3", "row[@accessiblename='Row 3']/cell[@accessiblename='colAusgang Row 3']", "", 30000, null, "5cb8ebc9-aa6e-41b3-9258-9f928ddb0e82");
                _colbektnr1row3Info = new RepoItemInfo(this, "ColBektNr1Row3", "row[@accessiblename='Row 3']/cell[@accessiblename='colBekt_nr1 Row 3']", "", 30000, null, "4b6f80a1-7943-4d66-b7aa-8d122d3c0f5e");
                _colktonrrow3Info = new RepoItemInfo(this, "ColKtoNrRow3", "row[@accessiblename='Row 3']/cell[@accessiblename='colKto_nr Row 3']", "", 30000, null, "3a8ed6c1-4bfb-4f4d-b36f-f0b2c932a240");
                _colsaldolfdrow3Info = new RepoItemInfo(this, "ColSaldoLfdRow3", "row[@accessiblename='Row 3']/cell[@accessiblename='colSaldo_lfd Row 3']", "", 30000, null, "c7b4bf8a-2d3c-48c0-b3f0-43d3f8d88deb");
                _row4column0Info = new RepoItemInfo(this, "Row4Column0", "row[@accessiblename='Row 4']/cell[@accessiblename='Row 4 Column 0']", "", 30000, null, "30d00d89-bc4a-4d1b-9549-d9a130deb48c");
                _colausgangrow4Info = new RepoItemInfo(this, "ColAusgangRow4", "row[@accessiblename='Row 4']/cell[@accessiblename='colAusgang Row 4']", "", 30000, null, "34519b4a-0a80-4c39-be61-99f865ddb221");
                _colustcoderow4Info = new RepoItemInfo(this, "ColUstcodeRow4", "row[@accessiblename='Row 4']/cell[@accessiblename='colUstcode Row 4']", "", 30000, null, "e50a5989-2fdc-4e8c-be56-c70a619998b5");
                _colktonrrow4Info = new RepoItemInfo(this, "ColKtoNrRow4", "row[@accessiblename='Row 4']/cell[@accessiblename='colKto_nr Row 4']", "", 30000, null, "234c918c-3753-4a43-b145-a8be624f529a");
                _colbektnr1row4Info = new RepoItemInfo(this, "ColBektNr1Row4", "row[@accessiblename='Row 4']/cell[@accessiblename='colBekt_nr1 Row 4']", "", 30000, null, "bef8c783-de95-489c-b523-186a8832b3d7");
                _coltagrow4Info = new RepoItemInfo(this, "ColTagRow4", "row[@accessiblename='Row 4']/cell[@accessiblename='colTag Row 4']", "", 30000, null, "521208fc-7e8b-4657-b310-fd287dc68ad6");
                _colbelegrow4Info = new RepoItemInfo(this, "ColBelegRow4", "row[@accessiblename='Row 4']/cell[@accessiblename='colBeleg Row 4']", "", 30000, null, "bb650403-ff08-4afe-bb40-81c23494fe1f");
                _colposrow4Info = new RepoItemInfo(this, "ColPosRow4", "row[@accessiblename='Row 4']/cell[@accessiblename='colPos Row 4']", "", 30000, null, "76466c82-a4cb-4f72-bb3f-6b4671aa1c3b");
                _coltextrow4Info = new RepoItemInfo(this, "ColTextRow4", "row[@accessiblename='Row 4']/cell[@accessiblename='colText Row 4']", "", 30000, null, "1ba55b80-e778-46be-bec2-43516cefc631");
                _colsaldolfdrow4Info = new RepoItemInfo(this, "ColSaldoLfdRow4", "row[@accessiblename='Row 4']/cell[@accessiblename='colSaldo_lfd Row 4']", "", 30000, null, "1d6e893f-7379-4c86-92db-61759b8c3835");
                _row5column0Info = new RepoItemInfo(this, "Row5Column0", "row[@accessiblename='Row 5']/cell[@accessiblename='Row 5 Column 0']", "", 30000, null, "0aec4446-6403-4cd7-96f3-763d5f9c40f0");
                _coltagrow5Info = new RepoItemInfo(this, "ColTagRow5", "row[@accessiblename='Row 5']/cell[@accessiblename='colTag Row 5']", "", 30000, null, "6137c447-6be5-4c60-9488-39e75a271525");
                _colbelegrow5Info = new RepoItemInfo(this, "ColBelegRow5", "row[@accessiblename='Row 5']/cell[@accessiblename='colBeleg Row 5']", "", 30000, null, "5e5940f9-b356-485f-9385-714a71d801c7");
                _colposrow5Info = new RepoItemInfo(this, "ColPosRow5", "row[@accessiblename='Row 5']/cell[@accessiblename='colPos Row 5']", "", 30000, null, "4fdb52cf-250f-42e6-8e7a-e34697ea2b4e");
                _coltextrow5Info = new RepoItemInfo(this, "ColTextRow5", "row[@accessiblename='Row 5']/cell[@accessiblename='colText Row 5']", "", 30000, null, "680dd3ae-f0bb-48bf-b1d3-25beb2f8a656");
                _coleingangrow5Info = new RepoItemInfo(this, "ColEingangRow5", "row[@accessiblename='Row 5']/cell[@accessiblename='colEingang Row 5']", "", 30000, null, "2e24cb74-8a0a-4ce6-874b-30f8e7bec86d");
                _colausgangrow5Info = new RepoItemInfo(this, "ColAusgangRow5", "row[@accessiblename='Row 5']/cell[@accessiblename='colAusgang Row 5']", "", 30000, null, "fa50eca9-82b8-49e8-a413-016ac93be0be");
                _colktonrrow5Info = new RepoItemInfo(this, "ColKtoNrRow5", "row[@accessiblename='Row 5']/cell[@accessiblename='colKto_nr Row 5']", "", 30000, null, "a596c37b-ae6a-4f89-b956-b1f4115f7029");
                _colbektnr1row5Info = new RepoItemInfo(this, "ColBektNr1Row5", "row[@accessiblename='Row 5']/cell[@accessiblename='colBekt_nr1 Row 5']", "", 30000, null, "8f27bda7-02be-434d-a57a-6a3ac09dc3ee");
                _colsaldolfdrow5Info = new RepoItemInfo(this, "ColSaldoLfdRow5", "row[@accessiblename='Row 5']/cell[@accessiblename='colSaldo_lfd Row 5']", "", 30000, null, "1daa0858-d923-4a1e-b10c-2e39c25f476e");
                _colfehlerrow5Info = new RepoItemInfo(this, "ColFehlerRow5", "row[@accessiblename='Row 5']/cell[@accessiblename='colFehler Row 5']", "", 30000, null, "71ec2ff7-5089-4a63-b15e-4e9500b8080e");
                _row6column0Info = new RepoItemInfo(this, "Row6Column0", "row[@accessiblename='Row 6']/cell[@accessiblename='Row 6 Column 0']", "", 30000, null, "f8a5152a-4289-4e5b-bbd6-53b4dafa9e38");
                _colausgangrow6Info = new RepoItemInfo(this, "ColAusgangRow6", "row[@accessiblename='Row 6']/cell[@accessiblename='colAusgang Row 6']", "", 30000, null, "3b48db56-e186-47fb-bc1a-c2e963fa1e1c");
                _coltagrow6Info = new RepoItemInfo(this, "ColTagRow6", "row[@accessiblename='Row 6']/cell[@accessiblename='colTag Row 6']", "", 30000, null, "10d35ba5-93ff-47e0-8d22-4d42776bba05");
                _colbelegrow6Info = new RepoItemInfo(this, "ColBelegRow6", "row[@accessiblename='Row 6']/cell[@accessiblename='colBeleg Row 6']", "", 30000, null, "243b064b-2042-4cd7-be56-8278e0f0e05e");
                _colposrow6Info = new RepoItemInfo(this, "ColPosRow6", "row[@accessiblename='Row 6']/cell[@accessiblename='colPos Row 6']", "", 30000, null, "d9d44bce-6af2-40e3-8d7e-ad162ed48044");
                _coltextrow6Info = new RepoItemInfo(this, "ColTextRow6", "row[@accessiblename='Row 6']/cell[@accessiblename='colText Row 6']", "", 30000, null, "555c3eb9-809d-4ee6-9395-815f4509b735");
                _colktonrrow6Info = new RepoItemInfo(this, "ColKtoNrRow6", "row[@accessiblename='Row 6']/cell[@accessiblename='colKto_nr Row 6']", "", 30000, null, "22b1d24c-361b-466e-95e3-e85007399170");
                _colustbetragrow6Info = new RepoItemInfo(this, "ColUstbetragRow6", "row[@accessiblename='Row 6']/cell[@accessiblename='colUstbetrag Row 6']", "", 30000, null, "316e9ed7-3194-4108-8bf2-ad83c0f45659");
                _colbektnr1row6Info = new RepoItemInfo(this, "ColBektNr1Row6", "row[@accessiblename='Row 6']/cell[@accessiblename='colBekt_nr1 Row 6']", "", 30000, null, "6ee4e15f-9e53-4e89-910c-b3495cc14277");
                _colsaldolfdrow6Info = new RepoItemInfo(this, "ColSaldoLfdRow6", "row[@accessiblename='Row 6']/cell[@accessiblename='colSaldo_lfd Row 6']", "", 30000, null, "449a2a46-13ef-41e1-8daf-1e27a25a01f5");
                _colausgangrow7Info = new RepoItemInfo(this, "ColAusgangRow7", "row[@accessiblename='Row 7']/cell[@accessiblename='colAusgang Row 7']", "", 30000, null, "2baabea3-b7f4-4ea6-b07d-163d9c7de26a");
                _coltagrow7Info = new RepoItemInfo(this, "ColTagRow7", "row[@accessiblename='Row 7']/cell[@accessiblename='colTag Row 7']", "", 30000, null, "213544ad-1556-4ec2-b9cd-93e456a7294f");
                _colbelegrow7Info = new RepoItemInfo(this, "ColBelegRow7", "row[@accessiblename='Row 7']/cell[@accessiblename='colBeleg Row 7']", "", 30000, null, "8264f114-9bce-4d0a-bec2-3006e7e6c7ac");
                _colposrow7Info = new RepoItemInfo(this, "ColPosRow7", "row[@accessiblename='Row 7']/cell[@accessiblename='colPos Row 7']", "", 30000, null, "ef537827-fd7b-46e5-b4d1-d326a746720a");
                _coltextrow7Info = new RepoItemInfo(this, "ColTextRow7", "row[@accessiblename='Row 7']/cell[@accessiblename='colText Row 7']", "", 30000, null, "0c07fc22-7712-45c5-8fcd-7bb9595e54f8");
                _colsaldolfdrow7Info = new RepoItemInfo(this, "ColSaldoLfdRow7", "row[@accessiblename='Row 7']/cell[@accessiblename='colSaldo_lfd Row 7']", "", 30000, null, "fab15990-63ec-43df-9c47-0894fc573130");
                _colbektnr1row7Info = new RepoItemInfo(this, "ColBektNr1Row7", "row[@accessiblename='Row 7']/cell[@accessiblename='colBekt_nr1 Row 7']", "", 30000, null, "aaaf85a8-bef6-466b-a78e-adbc83a74add");
                _colktonrrow7Info = new RepoItemInfo(this, "ColKtoNrRow7", "row[@accessiblename='Row 7']/cell[@accessiblename='colKto_nr Row 7']", "", 30000, null, "317e6619-0383-42a2-9e3c-e944d2604215");
                _coltagrow8Info = new RepoItemInfo(this, "ColTagRow8", "row[@accessiblename='Row 8']/cell[@accessiblename='colTag Row 8']", "", 30000, null, "3d0bcd28-0b64-4ad2-89e2-cc2e2f33a460");
                _colbelegrow8Info = new RepoItemInfo(this, "ColBelegRow8", "row[@accessiblename='Row 8']/cell[@accessiblename='colBeleg Row 8']", "", 30000, null, "5d4eb98f-d894-4229-ab74-a520f80b17b2");
                _colposrow8Info = new RepoItemInfo(this, "ColPosRow8", "row[@accessiblename='Row 8']/cell[@accessiblename='colPos Row 8']", "", 30000, null, "2072eb40-566b-4029-9d81-ac75f7f25fd4");
                _coltextrow8Info = new RepoItemInfo(this, "ColTextRow8", "row[@accessiblename='Row 8']/cell[@accessiblename='colText Row 8']", "", 30000, null, "9bc1bcb1-4f9d-422d-ad8b-ba8839535fc7");
                _colausgangrow8Info = new RepoItemInfo(this, "ColAusgangRow8", "row[@accessiblename='Row 8']/cell[@accessiblename='colAusgang Row 8']", "", 30000, null, "ed1ab60d-8ef1-4485-8c9f-9ee2c0130264");
                _colsaldolfdrow8Info = new RepoItemInfo(this, "ColSaldoLfdRow8", "row[@accessiblename='Row 8']/cell[@accessiblename='colSaldo_lfd Row 8']", "", 30000, null, "6d1e658f-48c1-414e-8484-7dd2d4383771");
                _colktonrrow8Info = new RepoItemInfo(this, "ColKtoNrRow8", "row[@accessiblename='Row 8']/cell[@accessiblename='colKto_nr Row 8']", "", 30000, null, "1bf18116-3f0e-42cb-95ea-09e9b287ebeb");
                _colbektnr1row8Info = new RepoItemInfo(this, "ColBektNr1Row8", "row[@accessiblename='Row 8']/cell[@accessiblename='colBekt_nr1 Row 8']", "", 30000, null, "70ce5f8d-62e7-4d17-bf2a-c325dce50ffb");
                _colustcoderow5Info = new RepoItemInfo(this, "ColUstcodeRow5", "row[@accessiblename='Row 5']/cell[@accessiblename='colUstcode Row 5']", "", 30000, null, "1b3b6ac7-cc35-47f0-b671-55278fde7e01");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("91b48de0-3fb7-4c42-b2a7-c661355eaaaf")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("91b48de0-3fb7-4c42-b2a7-c661355eaaaf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FlexGrid item.
            /// </summary>
            [RepositoryItem("a392e9b9-43c5-41f8-805e-17732e9fb1b2")]
            public virtual Ranorex.Table FlexGrid
            {
                get
                {
                    return _flexgridInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The FlexGrid item info.
            /// </summary>
            [RepositoryItemInfo("a392e9b9-43c5-41f8-805e-17732e9fb1b2")]
            public virtual RepoItemInfo FlexGridInfo
            {
                get
                {
                    return _flexgridInfo;
                }
            }

            /// <summary>
            /// The ColBukaKlRow0_Spaltenueberschrift item.
            /// </summary>
            [RepositoryItem("d4dbbd0a-4d6a-4cce-9a58-a3526591e613")]
            public virtual Ranorex.Cell ColBukaKlRow0_Spaltenueberschrift
            {
                get
                {
                    return _colbukaklrow0_spaltenueberschriftInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBukaKlRow0_Spaltenueberschrift item info.
            /// </summary>
            [RepositoryItemInfo("d4dbbd0a-4d6a-4cce-9a58-a3526591e613")]
            public virtual RepoItemInfo ColBukaKlRow0_SpaltenueberschriftInfo
            {
                get
                {
                    return _colbukaklrow0_spaltenueberschriftInfo;
                }
            }

            /// <summary>
            /// The ColTextRow1 item.
            /// </summary>
            [RepositoryItem("46ea5ab6-d92c-4767-b347-dddecb9ced4b")]
            public virtual Ranorex.Cell ColTextRow1
            {
                get
                {
                    return _coltextrow1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTextRow1 item info.
            /// </summary>
            [RepositoryItemInfo("46ea5ab6-d92c-4767-b347-dddecb9ced4b")]
            public virtual RepoItemInfo ColTextRow1Info
            {
                get
                {
                    return _coltextrow1Info;
                }
            }

            /// <summary>
            /// The Row3Column0 item.
            /// </summary>
            [RepositoryItem("8fd81c39-928d-4a40-bb91-369094cf488a")]
            public virtual Ranorex.Cell Row3Column0
            {
                get
                {
                    return _row3column0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Row3Column0 item info.
            /// </summary>
            [RepositoryItemInfo("8fd81c39-928d-4a40-bb91-369094cf488a")]
            public virtual RepoItemInfo Row3Column0Info
            {
                get
                {
                    return _row3column0Info;
                }
            }

            /// <summary>
            /// The ColTagRow3 item.
            /// </summary>
            [RepositoryItem("6dae7a08-c29e-4e06-8f9f-2ca57abfb9da")]
            public virtual Ranorex.Cell ColTagRow3
            {
                get
                {
                    return _coltagrow3Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTagRow3 item info.
            /// </summary>
            [RepositoryItemInfo("6dae7a08-c29e-4e06-8f9f-2ca57abfb9da")]
            public virtual RepoItemInfo ColTagRow3Info
            {
                get
                {
                    return _coltagrow3Info;
                }
            }

            /// <summary>
            /// The ColPosRow3 item.
            /// </summary>
            [RepositoryItem("e70f00b5-6532-4158-b5e7-0fb3c0ff9ab9")]
            public virtual Ranorex.Cell ColPosRow3
            {
                get
                {
                    return _colposrow3Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColPosRow3 item info.
            /// </summary>
            [RepositoryItemInfo("e70f00b5-6532-4158-b5e7-0fb3c0ff9ab9")]
            public virtual RepoItemInfo ColPosRow3Info
            {
                get
                {
                    return _colposrow3Info;
                }
            }

            /// <summary>
            /// The ColTextRow3 item.
            /// </summary>
            [RepositoryItem("b8ff2686-d69c-4550-b740-50a620bc359d")]
            public virtual Ranorex.Cell ColTextRow3
            {
                get
                {
                    return _coltextrow3Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTextRow3 item info.
            /// </summary>
            [RepositoryItemInfo("b8ff2686-d69c-4550-b740-50a620bc359d")]
            public virtual RepoItemInfo ColTextRow3Info
            {
                get
                {
                    return _coltextrow3Info;
                }
            }

            /// <summary>
            /// The ColAusgangRow3 item.
            /// </summary>
            [RepositoryItem("5cb8ebc9-aa6e-41b3-9258-9f928ddb0e82")]
            public virtual Ranorex.Cell ColAusgangRow3
            {
                get
                {
                    return _colausgangrow3Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColAusgangRow3 item info.
            /// </summary>
            [RepositoryItemInfo("5cb8ebc9-aa6e-41b3-9258-9f928ddb0e82")]
            public virtual RepoItemInfo ColAusgangRow3Info
            {
                get
                {
                    return _colausgangrow3Info;
                }
            }

            /// <summary>
            /// The ColBektNr1Row3 item.
            /// </summary>
            [RepositoryItem("4b6f80a1-7943-4d66-b7aa-8d122d3c0f5e")]
            public virtual Ranorex.Cell ColBektNr1Row3
            {
                get
                {
                    return _colbektnr1row3Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBektNr1Row3 item info.
            /// </summary>
            [RepositoryItemInfo("4b6f80a1-7943-4d66-b7aa-8d122d3c0f5e")]
            public virtual RepoItemInfo ColBektNr1Row3Info
            {
                get
                {
                    return _colbektnr1row3Info;
                }
            }

            /// <summary>
            /// The ColKtoNrRow3 item.
            /// </summary>
            [RepositoryItem("3a8ed6c1-4bfb-4f4d-b36f-f0b2c932a240")]
            public virtual Ranorex.Cell ColKtoNrRow3
            {
                get
                {
                    return _colktonrrow3Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColKtoNrRow3 item info.
            /// </summary>
            [RepositoryItemInfo("3a8ed6c1-4bfb-4f4d-b36f-f0b2c932a240")]
            public virtual RepoItemInfo ColKtoNrRow3Info
            {
                get
                {
                    return _colktonrrow3Info;
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow3 item.
            /// </summary>
            [RepositoryItem("c7b4bf8a-2d3c-48c0-b3f0-43d3f8d88deb")]
            public virtual Ranorex.Cell ColSaldoLfdRow3
            {
                get
                {
                    return _colsaldolfdrow3Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow3 item info.
            /// </summary>
            [RepositoryItemInfo("c7b4bf8a-2d3c-48c0-b3f0-43d3f8d88deb")]
            public virtual RepoItemInfo ColSaldoLfdRow3Info
            {
                get
                {
                    return _colsaldolfdrow3Info;
                }
            }

            /// <summary>
            /// The Row4Column0 item.
            /// </summary>
            [RepositoryItem("30d00d89-bc4a-4d1b-9549-d9a130deb48c")]
            public virtual Ranorex.Cell Row4Column0
            {
                get
                {
                    return _row4column0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Row4Column0 item info.
            /// </summary>
            [RepositoryItemInfo("30d00d89-bc4a-4d1b-9549-d9a130deb48c")]
            public virtual RepoItemInfo Row4Column0Info
            {
                get
                {
                    return _row4column0Info;
                }
            }

            /// <summary>
            /// The ColAusgangRow4 item.
            /// </summary>
            [RepositoryItem("34519b4a-0a80-4c39-be61-99f865ddb221")]
            public virtual Ranorex.Cell ColAusgangRow4
            {
                get
                {
                    return _colausgangrow4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColAusgangRow4 item info.
            /// </summary>
            [RepositoryItemInfo("34519b4a-0a80-4c39-be61-99f865ddb221")]
            public virtual RepoItemInfo ColAusgangRow4Info
            {
                get
                {
                    return _colausgangrow4Info;
                }
            }

            /// <summary>
            /// The ColUstcodeRow4 item.
            /// </summary>
            [RepositoryItem("e50a5989-2fdc-4e8c-be56-c70a619998b5")]
            public virtual Ranorex.Cell ColUstcodeRow4
            {
                get
                {
                    return _colustcoderow4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColUstcodeRow4 item info.
            /// </summary>
            [RepositoryItemInfo("e50a5989-2fdc-4e8c-be56-c70a619998b5")]
            public virtual RepoItemInfo ColUstcodeRow4Info
            {
                get
                {
                    return _colustcoderow4Info;
                }
            }

            /// <summary>
            /// The ColKtoNrRow4 item.
            /// </summary>
            [RepositoryItem("234c918c-3753-4a43-b145-a8be624f529a")]
            public virtual Ranorex.Cell ColKtoNrRow4
            {
                get
                {
                    return _colktonrrow4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColKtoNrRow4 item info.
            /// </summary>
            [RepositoryItemInfo("234c918c-3753-4a43-b145-a8be624f529a")]
            public virtual RepoItemInfo ColKtoNrRow4Info
            {
                get
                {
                    return _colktonrrow4Info;
                }
            }

            /// <summary>
            /// The ColBektNr1Row4 item.
            /// </summary>
            [RepositoryItem("bef8c783-de95-489c-b523-186a8832b3d7")]
            public virtual Ranorex.Cell ColBektNr1Row4
            {
                get
                {
                    return _colbektnr1row4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBektNr1Row4 item info.
            /// </summary>
            [RepositoryItemInfo("bef8c783-de95-489c-b523-186a8832b3d7")]
            public virtual RepoItemInfo ColBektNr1Row4Info
            {
                get
                {
                    return _colbektnr1row4Info;
                }
            }

            /// <summary>
            /// The ColTagRow4 item.
            /// </summary>
            [RepositoryItem("521208fc-7e8b-4657-b310-fd287dc68ad6")]
            public virtual Ranorex.Cell ColTagRow4
            {
                get
                {
                    return _coltagrow4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTagRow4 item info.
            /// </summary>
            [RepositoryItemInfo("521208fc-7e8b-4657-b310-fd287dc68ad6")]
            public virtual RepoItemInfo ColTagRow4Info
            {
                get
                {
                    return _coltagrow4Info;
                }
            }

            /// <summary>
            /// The ColBelegRow4 item.
            /// </summary>
            [RepositoryItem("bb650403-ff08-4afe-bb40-81c23494fe1f")]
            public virtual Ranorex.Cell ColBelegRow4
            {
                get
                {
                    return _colbelegrow4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBelegRow4 item info.
            /// </summary>
            [RepositoryItemInfo("bb650403-ff08-4afe-bb40-81c23494fe1f")]
            public virtual RepoItemInfo ColBelegRow4Info
            {
                get
                {
                    return _colbelegrow4Info;
                }
            }

            /// <summary>
            /// The ColPosRow4 item.
            /// </summary>
            [RepositoryItem("76466c82-a4cb-4f72-bb3f-6b4671aa1c3b")]
            public virtual Ranorex.Cell ColPosRow4
            {
                get
                {
                    return _colposrow4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColPosRow4 item info.
            /// </summary>
            [RepositoryItemInfo("76466c82-a4cb-4f72-bb3f-6b4671aa1c3b")]
            public virtual RepoItemInfo ColPosRow4Info
            {
                get
                {
                    return _colposrow4Info;
                }
            }

            /// <summary>
            /// The ColTextRow4 item.
            /// </summary>
            [RepositoryItem("1ba55b80-e778-46be-bec2-43516cefc631")]
            public virtual Ranorex.Cell ColTextRow4
            {
                get
                {
                    return _coltextrow4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTextRow4 item info.
            /// </summary>
            [RepositoryItemInfo("1ba55b80-e778-46be-bec2-43516cefc631")]
            public virtual RepoItemInfo ColTextRow4Info
            {
                get
                {
                    return _coltextrow4Info;
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow4 item.
            /// </summary>
            [RepositoryItem("1d6e893f-7379-4c86-92db-61759b8c3835")]
            public virtual Ranorex.Cell ColSaldoLfdRow4
            {
                get
                {
                    return _colsaldolfdrow4Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow4 item info.
            /// </summary>
            [RepositoryItemInfo("1d6e893f-7379-4c86-92db-61759b8c3835")]
            public virtual RepoItemInfo ColSaldoLfdRow4Info
            {
                get
                {
                    return _colsaldolfdrow4Info;
                }
            }

            /// <summary>
            /// The Row5Column0 item.
            /// </summary>
            [RepositoryItem("0aec4446-6403-4cd7-96f3-763d5f9c40f0")]
            public virtual Ranorex.Cell Row5Column0
            {
                get
                {
                    return _row5column0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Row5Column0 item info.
            /// </summary>
            [RepositoryItemInfo("0aec4446-6403-4cd7-96f3-763d5f9c40f0")]
            public virtual RepoItemInfo Row5Column0Info
            {
                get
                {
                    return _row5column0Info;
                }
            }

            /// <summary>
            /// The ColTagRow5 item.
            /// </summary>
            [RepositoryItem("6137c447-6be5-4c60-9488-39e75a271525")]
            public virtual Ranorex.Cell ColTagRow5
            {
                get
                {
                    return _coltagrow5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTagRow5 item info.
            /// </summary>
            [RepositoryItemInfo("6137c447-6be5-4c60-9488-39e75a271525")]
            public virtual RepoItemInfo ColTagRow5Info
            {
                get
                {
                    return _coltagrow5Info;
                }
            }

            /// <summary>
            /// The ColBelegRow5 item.
            /// </summary>
            [RepositoryItem("5e5940f9-b356-485f-9385-714a71d801c7")]
            public virtual Ranorex.Cell ColBelegRow5
            {
                get
                {
                    return _colbelegrow5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBelegRow5 item info.
            /// </summary>
            [RepositoryItemInfo("5e5940f9-b356-485f-9385-714a71d801c7")]
            public virtual RepoItemInfo ColBelegRow5Info
            {
                get
                {
                    return _colbelegrow5Info;
                }
            }

            /// <summary>
            /// The ColPosRow5 item.
            /// </summary>
            [RepositoryItem("4fdb52cf-250f-42e6-8e7a-e34697ea2b4e")]
            public virtual Ranorex.Cell ColPosRow5
            {
                get
                {
                    return _colposrow5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColPosRow5 item info.
            /// </summary>
            [RepositoryItemInfo("4fdb52cf-250f-42e6-8e7a-e34697ea2b4e")]
            public virtual RepoItemInfo ColPosRow5Info
            {
                get
                {
                    return _colposrow5Info;
                }
            }

            /// <summary>
            /// The ColTextRow5 item.
            /// </summary>
            [RepositoryItem("680dd3ae-f0bb-48bf-b1d3-25beb2f8a656")]
            public virtual Ranorex.Cell ColTextRow5
            {
                get
                {
                    return _coltextrow5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTextRow5 item info.
            /// </summary>
            [RepositoryItemInfo("680dd3ae-f0bb-48bf-b1d3-25beb2f8a656")]
            public virtual RepoItemInfo ColTextRow5Info
            {
                get
                {
                    return _coltextrow5Info;
                }
            }

            /// <summary>
            /// The ColEingangRow5 item.
            /// </summary>
            [RepositoryItem("2e24cb74-8a0a-4ce6-874b-30f8e7bec86d")]
            public virtual Ranorex.Cell ColEingangRow5
            {
                get
                {
                    return _coleingangrow5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColEingangRow5 item info.
            /// </summary>
            [RepositoryItemInfo("2e24cb74-8a0a-4ce6-874b-30f8e7bec86d")]
            public virtual RepoItemInfo ColEingangRow5Info
            {
                get
                {
                    return _coleingangrow5Info;
                }
            }

            /// <summary>
            /// The ColAusgangRow5 item.
            /// </summary>
            [RepositoryItem("fa50eca9-82b8-49e8-a413-016ac93be0be")]
            public virtual Ranorex.Cell ColAusgangRow5
            {
                get
                {
                    return _colausgangrow5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColAusgangRow5 item info.
            /// </summary>
            [RepositoryItemInfo("fa50eca9-82b8-49e8-a413-016ac93be0be")]
            public virtual RepoItemInfo ColAusgangRow5Info
            {
                get
                {
                    return _colausgangrow5Info;
                }
            }

            /// <summary>
            /// The ColKtoNrRow5 item.
            /// </summary>
            [RepositoryItem("a596c37b-ae6a-4f89-b956-b1f4115f7029")]
            public virtual Ranorex.Cell ColKtoNrRow5
            {
                get
                {
                    return _colktonrrow5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColKtoNrRow5 item info.
            /// </summary>
            [RepositoryItemInfo("a596c37b-ae6a-4f89-b956-b1f4115f7029")]
            public virtual RepoItemInfo ColKtoNrRow5Info
            {
                get
                {
                    return _colktonrrow5Info;
                }
            }

            /// <summary>
            /// The ColBektNr1Row5 item.
            /// </summary>
            [RepositoryItem("8f27bda7-02be-434d-a57a-6a3ac09dc3ee")]
            public virtual Ranorex.Cell ColBektNr1Row5
            {
                get
                {
                    return _colbektnr1row5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBektNr1Row5 item info.
            /// </summary>
            [RepositoryItemInfo("8f27bda7-02be-434d-a57a-6a3ac09dc3ee")]
            public virtual RepoItemInfo ColBektNr1Row5Info
            {
                get
                {
                    return _colbektnr1row5Info;
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow5 item.
            /// </summary>
            [RepositoryItem("1daa0858-d923-4a1e-b10c-2e39c25f476e")]
            public virtual Ranorex.Cell ColSaldoLfdRow5
            {
                get
                {
                    return _colsaldolfdrow5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow5 item info.
            /// </summary>
            [RepositoryItemInfo("1daa0858-d923-4a1e-b10c-2e39c25f476e")]
            public virtual RepoItemInfo ColSaldoLfdRow5Info
            {
                get
                {
                    return _colsaldolfdrow5Info;
                }
            }

            /// <summary>
            /// The ColFehlerRow5 item.
            /// </summary>
            [RepositoryItem("71ec2ff7-5089-4a63-b15e-4e9500b8080e")]
            public virtual Ranorex.Cell ColFehlerRow5
            {
                get
                {
                    return _colfehlerrow5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColFehlerRow5 item info.
            /// </summary>
            [RepositoryItemInfo("71ec2ff7-5089-4a63-b15e-4e9500b8080e")]
            public virtual RepoItemInfo ColFehlerRow5Info
            {
                get
                {
                    return _colfehlerrow5Info;
                }
            }

            /// <summary>
            /// The Row6Column0 item.
            /// </summary>
            [RepositoryItem("f8a5152a-4289-4e5b-bbd6-53b4dafa9e38")]
            public virtual Ranorex.Cell Row6Column0
            {
                get
                {
                    return _row6column0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Row6Column0 item info.
            /// </summary>
            [RepositoryItemInfo("f8a5152a-4289-4e5b-bbd6-53b4dafa9e38")]
            public virtual RepoItemInfo Row6Column0Info
            {
                get
                {
                    return _row6column0Info;
                }
            }

            /// <summary>
            /// The ColAusgangRow6 item.
            /// </summary>
            [RepositoryItem("3b48db56-e186-47fb-bc1a-c2e963fa1e1c")]
            public virtual Ranorex.Cell ColAusgangRow6
            {
                get
                {
                    return _colausgangrow6Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColAusgangRow6 item info.
            /// </summary>
            [RepositoryItemInfo("3b48db56-e186-47fb-bc1a-c2e963fa1e1c")]
            public virtual RepoItemInfo ColAusgangRow6Info
            {
                get
                {
                    return _colausgangrow6Info;
                }
            }

            /// <summary>
            /// The ColTagRow6 item.
            /// </summary>
            [RepositoryItem("10d35ba5-93ff-47e0-8d22-4d42776bba05")]
            public virtual Ranorex.Cell ColTagRow6
            {
                get
                {
                    return _coltagrow6Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTagRow6 item info.
            /// </summary>
            [RepositoryItemInfo("10d35ba5-93ff-47e0-8d22-4d42776bba05")]
            public virtual RepoItemInfo ColTagRow6Info
            {
                get
                {
                    return _coltagrow6Info;
                }
            }

            /// <summary>
            /// The ColBelegRow6 item.
            /// </summary>
            [RepositoryItem("243b064b-2042-4cd7-be56-8278e0f0e05e")]
            public virtual Ranorex.Cell ColBelegRow6
            {
                get
                {
                    return _colbelegrow6Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBelegRow6 item info.
            /// </summary>
            [RepositoryItemInfo("243b064b-2042-4cd7-be56-8278e0f0e05e")]
            public virtual RepoItemInfo ColBelegRow6Info
            {
                get
                {
                    return _colbelegrow6Info;
                }
            }

            /// <summary>
            /// The ColPosRow6 item.
            /// </summary>
            [RepositoryItem("d9d44bce-6af2-40e3-8d7e-ad162ed48044")]
            public virtual Ranorex.Cell ColPosRow6
            {
                get
                {
                    return _colposrow6Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColPosRow6 item info.
            /// </summary>
            [RepositoryItemInfo("d9d44bce-6af2-40e3-8d7e-ad162ed48044")]
            public virtual RepoItemInfo ColPosRow6Info
            {
                get
                {
                    return _colposrow6Info;
                }
            }

            /// <summary>
            /// The ColTextRow6 item.
            /// </summary>
            [RepositoryItem("555c3eb9-809d-4ee6-9395-815f4509b735")]
            public virtual Ranorex.Cell ColTextRow6
            {
                get
                {
                    return _coltextrow6Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTextRow6 item info.
            /// </summary>
            [RepositoryItemInfo("555c3eb9-809d-4ee6-9395-815f4509b735")]
            public virtual RepoItemInfo ColTextRow6Info
            {
                get
                {
                    return _coltextrow6Info;
                }
            }

            /// <summary>
            /// The ColKtoNrRow6 item.
            /// </summary>
            [RepositoryItem("22b1d24c-361b-466e-95e3-e85007399170")]
            public virtual Ranorex.Cell ColKtoNrRow6
            {
                get
                {
                    return _colktonrrow6Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColKtoNrRow6 item info.
            /// </summary>
            [RepositoryItemInfo("22b1d24c-361b-466e-95e3-e85007399170")]
            public virtual RepoItemInfo ColKtoNrRow6Info
            {
                get
                {
                    return _colktonrrow6Info;
                }
            }

            /// <summary>
            /// The ColUstbetragRow6 item.
            /// </summary>
            [RepositoryItem("316e9ed7-3194-4108-8bf2-ad83c0f45659")]
            public virtual Ranorex.Cell ColUstbetragRow6
            {
                get
                {
                    return _colustbetragrow6Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColUstbetragRow6 item info.
            /// </summary>
            [RepositoryItemInfo("316e9ed7-3194-4108-8bf2-ad83c0f45659")]
            public virtual RepoItemInfo ColUstbetragRow6Info
            {
                get
                {
                    return _colustbetragrow6Info;
                }
            }

            /// <summary>
            /// The ColBektNr1Row6 item.
            /// </summary>
            [RepositoryItem("6ee4e15f-9e53-4e89-910c-b3495cc14277")]
            public virtual Ranorex.Cell ColBektNr1Row6
            {
                get
                {
                    return _colbektnr1row6Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBektNr1Row6 item info.
            /// </summary>
            [RepositoryItemInfo("6ee4e15f-9e53-4e89-910c-b3495cc14277")]
            public virtual RepoItemInfo ColBektNr1Row6Info
            {
                get
                {
                    return _colbektnr1row6Info;
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow6 item.
            /// </summary>
            [RepositoryItem("449a2a46-13ef-41e1-8daf-1e27a25a01f5")]
            public virtual Ranorex.Cell ColSaldoLfdRow6
            {
                get
                {
                    return _colsaldolfdrow6Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow6 item info.
            /// </summary>
            [RepositoryItemInfo("449a2a46-13ef-41e1-8daf-1e27a25a01f5")]
            public virtual RepoItemInfo ColSaldoLfdRow6Info
            {
                get
                {
                    return _colsaldolfdrow6Info;
                }
            }

            /// <summary>
            /// The ColAusgangRow7 item.
            /// </summary>
            [RepositoryItem("2baabea3-b7f4-4ea6-b07d-163d9c7de26a")]
            public virtual Ranorex.Cell ColAusgangRow7
            {
                get
                {
                    return _colausgangrow7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColAusgangRow7 item info.
            /// </summary>
            [RepositoryItemInfo("2baabea3-b7f4-4ea6-b07d-163d9c7de26a")]
            public virtual RepoItemInfo ColAusgangRow7Info
            {
                get
                {
                    return _colausgangrow7Info;
                }
            }

            /// <summary>
            /// The ColTagRow7 item.
            /// </summary>
            [RepositoryItem("213544ad-1556-4ec2-b9cd-93e456a7294f")]
            public virtual Ranorex.Cell ColTagRow7
            {
                get
                {
                    return _coltagrow7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTagRow7 item info.
            /// </summary>
            [RepositoryItemInfo("213544ad-1556-4ec2-b9cd-93e456a7294f")]
            public virtual RepoItemInfo ColTagRow7Info
            {
                get
                {
                    return _coltagrow7Info;
                }
            }

            /// <summary>
            /// The ColBelegRow7 item.
            /// </summary>
            [RepositoryItem("8264f114-9bce-4d0a-bec2-3006e7e6c7ac")]
            public virtual Ranorex.Cell ColBelegRow7
            {
                get
                {
                    return _colbelegrow7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBelegRow7 item info.
            /// </summary>
            [RepositoryItemInfo("8264f114-9bce-4d0a-bec2-3006e7e6c7ac")]
            public virtual RepoItemInfo ColBelegRow7Info
            {
                get
                {
                    return _colbelegrow7Info;
                }
            }

            /// <summary>
            /// The ColPosRow7 item.
            /// </summary>
            [RepositoryItem("ef537827-fd7b-46e5-b4d1-d326a746720a")]
            public virtual Ranorex.Cell ColPosRow7
            {
                get
                {
                    return _colposrow7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColPosRow7 item info.
            /// </summary>
            [RepositoryItemInfo("ef537827-fd7b-46e5-b4d1-d326a746720a")]
            public virtual RepoItemInfo ColPosRow7Info
            {
                get
                {
                    return _colposrow7Info;
                }
            }

            /// <summary>
            /// The ColTextRow7 item.
            /// </summary>
            [RepositoryItem("0c07fc22-7712-45c5-8fcd-7bb9595e54f8")]
            public virtual Ranorex.Cell ColTextRow7
            {
                get
                {
                    return _coltextrow7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTextRow7 item info.
            /// </summary>
            [RepositoryItemInfo("0c07fc22-7712-45c5-8fcd-7bb9595e54f8")]
            public virtual RepoItemInfo ColTextRow7Info
            {
                get
                {
                    return _coltextrow7Info;
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow7 item.
            /// </summary>
            [RepositoryItem("fab15990-63ec-43df-9c47-0894fc573130")]
            public virtual Ranorex.Cell ColSaldoLfdRow7
            {
                get
                {
                    return _colsaldolfdrow7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow7 item info.
            /// </summary>
            [RepositoryItemInfo("fab15990-63ec-43df-9c47-0894fc573130")]
            public virtual RepoItemInfo ColSaldoLfdRow7Info
            {
                get
                {
                    return _colsaldolfdrow7Info;
                }
            }

            /// <summary>
            /// The ColBektNr1Row7 item.
            /// </summary>
            [RepositoryItem("aaaf85a8-bef6-466b-a78e-adbc83a74add")]
            public virtual Ranorex.Cell ColBektNr1Row7
            {
                get
                {
                    return _colbektnr1row7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBektNr1Row7 item info.
            /// </summary>
            [RepositoryItemInfo("aaaf85a8-bef6-466b-a78e-adbc83a74add")]
            public virtual RepoItemInfo ColBektNr1Row7Info
            {
                get
                {
                    return _colbektnr1row7Info;
                }
            }

            /// <summary>
            /// The ColKtoNrRow7 item.
            /// </summary>
            [RepositoryItem("317e6619-0383-42a2-9e3c-e944d2604215")]
            public virtual Ranorex.Cell ColKtoNrRow7
            {
                get
                {
                    return _colktonrrow7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColKtoNrRow7 item info.
            /// </summary>
            [RepositoryItemInfo("317e6619-0383-42a2-9e3c-e944d2604215")]
            public virtual RepoItemInfo ColKtoNrRow7Info
            {
                get
                {
                    return _colktonrrow7Info;
                }
            }

            /// <summary>
            /// The ColTagRow8 item.
            /// </summary>
            [RepositoryItem("3d0bcd28-0b64-4ad2-89e2-cc2e2f33a460")]
            public virtual Ranorex.Cell ColTagRow8
            {
                get
                {
                    return _coltagrow8Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTagRow8 item info.
            /// </summary>
            [RepositoryItemInfo("3d0bcd28-0b64-4ad2-89e2-cc2e2f33a460")]
            public virtual RepoItemInfo ColTagRow8Info
            {
                get
                {
                    return _coltagrow8Info;
                }
            }

            /// <summary>
            /// The ColBelegRow8 item.
            /// </summary>
            [RepositoryItem("5d4eb98f-d894-4229-ab74-a520f80b17b2")]
            public virtual Ranorex.Cell ColBelegRow8
            {
                get
                {
                    return _colbelegrow8Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBelegRow8 item info.
            /// </summary>
            [RepositoryItemInfo("5d4eb98f-d894-4229-ab74-a520f80b17b2")]
            public virtual RepoItemInfo ColBelegRow8Info
            {
                get
                {
                    return _colbelegrow8Info;
                }
            }

            /// <summary>
            /// The ColPosRow8 item.
            /// </summary>
            [RepositoryItem("2072eb40-566b-4029-9d81-ac75f7f25fd4")]
            public virtual Ranorex.Cell ColPosRow8
            {
                get
                {
                    return _colposrow8Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColPosRow8 item info.
            /// </summary>
            [RepositoryItemInfo("2072eb40-566b-4029-9d81-ac75f7f25fd4")]
            public virtual RepoItemInfo ColPosRow8Info
            {
                get
                {
                    return _colposrow8Info;
                }
            }

            /// <summary>
            /// The ColTextRow8 item.
            /// </summary>
            [RepositoryItem("9bc1bcb1-4f9d-422d-ad8b-ba8839535fc7")]
            public virtual Ranorex.Cell ColTextRow8
            {
                get
                {
                    return _coltextrow8Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColTextRow8 item info.
            /// </summary>
            [RepositoryItemInfo("9bc1bcb1-4f9d-422d-ad8b-ba8839535fc7")]
            public virtual RepoItemInfo ColTextRow8Info
            {
                get
                {
                    return _coltextrow8Info;
                }
            }

            /// <summary>
            /// The ColAusgangRow8 item.
            /// </summary>
            [RepositoryItem("ed1ab60d-8ef1-4485-8c9f-9ee2c0130264")]
            public virtual Ranorex.Cell ColAusgangRow8
            {
                get
                {
                    return _colausgangrow8Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColAusgangRow8 item info.
            /// </summary>
            [RepositoryItemInfo("ed1ab60d-8ef1-4485-8c9f-9ee2c0130264")]
            public virtual RepoItemInfo ColAusgangRow8Info
            {
                get
                {
                    return _colausgangrow8Info;
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow8 item.
            /// </summary>
            [RepositoryItem("6d1e658f-48c1-414e-8484-7dd2d4383771")]
            public virtual Ranorex.Cell ColSaldoLfdRow8
            {
                get
                {
                    return _colsaldolfdrow8Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColSaldoLfdRow8 item info.
            /// </summary>
            [RepositoryItemInfo("6d1e658f-48c1-414e-8484-7dd2d4383771")]
            public virtual RepoItemInfo ColSaldoLfdRow8Info
            {
                get
                {
                    return _colsaldolfdrow8Info;
                }
            }

            /// <summary>
            /// The ColKtoNrRow8 item.
            /// </summary>
            [RepositoryItem("1bf18116-3f0e-42cb-95ea-09e9b287ebeb")]
            public virtual Ranorex.Cell ColKtoNrRow8
            {
                get
                {
                    return _colktonrrow8Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColKtoNrRow8 item info.
            /// </summary>
            [RepositoryItemInfo("1bf18116-3f0e-42cb-95ea-09e9b287ebeb")]
            public virtual RepoItemInfo ColKtoNrRow8Info
            {
                get
                {
                    return _colktonrrow8Info;
                }
            }

            /// <summary>
            /// The ColBektNr1Row8 item.
            /// </summary>
            [RepositoryItem("70ce5f8d-62e7-4d17-bf2a-c325dce50ffb")]
            public virtual Ranorex.Cell ColBektNr1Row8
            {
                get
                {
                    return _colbektnr1row8Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColBektNr1Row8 item info.
            /// </summary>
            [RepositoryItemInfo("70ce5f8d-62e7-4d17-bf2a-c325dce50ffb")]
            public virtual RepoItemInfo ColBektNr1Row8Info
            {
                get
                {
                    return _colbektnr1row8Info;
                }
            }

            /// <summary>
            /// The ColUstcodeRow5 item.
            /// </summary>
            [RepositoryItem("1b3b6ac7-cc35-47f0-b671-55278fde7e01")]
            public virtual Ranorex.Cell ColUstcodeRow5
            {
                get
                {
                    return _colustcoderow5Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The ColUstcodeRow5 item info.
            /// </summary>
            [RepositoryItemInfo("1b3b6ac7-cc35-47f0-b671-55278fde7e01")]
            public virtual RepoItemInfo ColUstcodeRow5Info
            {
                get
                {
                    return _colustcoderow5Info;
                }
            }
        }

        /// <summary>
        /// The BBUKAAppFolder folder.
        /// </summary>
        [RepositoryFolder("c33ea8f1-8c56-410b-b0e3-e45403c20370")]
        public partial class BBUKAAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _zeileeinfuegenInfo;

            /// <summary>
            /// Creates a new BBUKA  folder.
            /// </summary>
            public BBUKAAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BBUKA", "/contextmenu[@processname='B_BUKA']", parentFolder, 30000, null, true, "c33ea8f1-8c56-410b-b0e3-e45403c20370", "")
            {
                _zeileeinfuegenInfo = new RepoItemInfo(this, "ZeileEinfuegen", "menuitem[@accessiblename='Zeile einfügen']", "", 30000, null, "70b61f65-fcad-4b7b-a022-11ab799e292a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c33ea8f1-8c56-410b-b0e3-e45403c20370")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c33ea8f1-8c56-410b-b0e3-e45403c20370")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ZeileEinfuegen item.
            /// </summary>
            [RepositoryItem("70b61f65-fcad-4b7b-a022-11ab799e292a")]
            public virtual Ranorex.MenuItem ZeileEinfuegen
            {
                get
                {
                    return _zeileeinfuegenInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ZeileEinfuegen item info.
            /// </summary>
            [RepositoryItemInfo("70b61f65-fcad-4b7b-a022-11ab799e292a")]
            public virtual RepoItemInfo ZeileEinfuegenInfo
            {
                get
                {
                    return _zeileeinfuegenInfo;
                }
            }
        }

        /// <summary>
        /// The DlgMessageBoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("ef7ffc8a-b7c9-4b2c-b929-009bcccd4558")]
        public partial class DlgMessageBoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button0Info;
            RepoItemInfo _labelmeldungstextInfo;

            /// <summary>
            /// Creates a new DlgMessageBox  folder.
            /// </summary>
            public DlgMessageBoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DlgMessageBox", "/form[@controlname='dlgMessageBox']", parentFolder, 30000, null, true, "ef7ffc8a-b7c9-4b2c-b929-009bcccd4558", "")
            {
                _button0Info = new RepoItemInfo(this, "Button0", "button[@controlname='button0']", "", 30000, null, "32a8c1c4-6640-44b0-9e35-8e378409931b");
                _labelmeldungstextInfo = new RepoItemInfo(this, "LabelMeldungstext", "text[@controlname='labelMeldungstext']", "", 30000, null, "ef613fb8-1963-421d-839f-29986cc41e67");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ef7ffc8a-b7c9-4b2c-b929-009bcccd4558")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ef7ffc8a-b7c9-4b2c-b929-009bcccd4558")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button0 item.
            /// </summary>
            [RepositoryItem("32a8c1c4-6640-44b0-9e35-8e378409931b")]
            public virtual Ranorex.Button Button0
            {
                get
                {
                    return _button0Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button0 item info.
            /// </summary>
            [RepositoryItemInfo("32a8c1c4-6640-44b0-9e35-8e378409931b")]
            public virtual RepoItemInfo Button0Info
            {
                get
                {
                    return _button0Info;
                }
            }

            /// <summary>
            /// The LabelMeldungstext item.
            /// </summary>
            [RepositoryItem("ef613fb8-1963-421d-839f-29986cc41e67")]
            public virtual Ranorex.Text LabelMeldungstext
            {
                get
                {
                    return _labelmeldungstextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LabelMeldungstext item info.
            /// </summary>
            [RepositoryItemInfo("ef613fb8-1963-421d-839f-29986cc41e67")]
            public virtual RepoItemInfo LabelMeldungstextInfo
            {
                get
                {
                    return _labelmeldungstextInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
