///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N_ANLA_002.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Umbuchung_Maske_2 recording.
    /// </summary>
    [TestModule("bb177c96-7ab1-458f-8a27-5d4ec8c82419", ModuleType.Recording, 1)]
    public partial class Umbuchung_Maske_2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::N_ANLA_002.N_ANLA_002Repository repository.
        /// </summary>
        public static global::N_ANLA_002.N_ANLA_002Repository repo = global::N_ANLA_002.N_ANLA_002Repository.Instance;

        static Umbuchung_Maske_2 instance = new Umbuchung_Maske_2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Umbuchung_Maske_2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Umbuchung_Maske_2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 2m to exist. Associated repository item: 'DlgUmbuch.TitleBar100UmbuchungAufNeueAnlage'", repo.DlgUmbuch.TitleBar100UmbuchungAufNeueAnlageInfo, new ActionTimeout(120000), new RecordItemIndex(0));
            repo.DlgUmbuch.TitleBar100UmbuchungAufNeueAnlageInfo.WaitForExists(120000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>'Umbuchung auf neue Anlage ') on item 'DlgUmbuch.TitleBar100UmbuchungAufNeueAnlage'.", repo.DlgUmbuch.TitleBar100UmbuchungAufNeueAnlageInfo, new RecordItemIndex(1));
            Validate.AttributeContains(repo.DlgUmbuch.TitleBar100UmbuchungAufNeueAnlageInfo, "Text", "Umbuchung auf neue Anlage ");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DlgUmbuch.CbGleicheAnlanr' at Center.", repo.DlgUmbuch.CbGleicheAnlanrInfo, new RecordItemIndex(2));
            repo.DlgUmbuch.CbGleicheAnlanr.Click();
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='yourtext') on item 'DlgUmbuch.CbGleicheAnlanr'.", repo.DlgUmbuch.CbGleicheAnlanrInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.DlgUmbuch.CbGleicheAnlanrInfo, "Text", "yourtext");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DlgUmbuch.PbOk' at Center.", repo.DlgUmbuch.PbOkInfo, new RecordItemIndex(4));
            repo.DlgUmbuch.PbOk.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
