///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace S_ALLTAB_Schnelltest.Recordings_UST
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Aenderung_UST_Code_Konten recording.
    /// </summary>
    [TestModule("e15f3ead-5f7a-4b18-a046-3daf1ccbed57", ModuleType.Recording, 1)]
    public partial class Aenderung_UST_Code_Konten : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::S_ALLTAB_Schnelltest.S_ALLTAB_SchnelltestRepository repository.
        /// </summary>
        public static global::S_ALLTAB_Schnelltest.S_ALLTAB_SchnelltestRepository repo = global::S_ALLTAB_Schnelltest.S_ALLTAB_SchnelltestRepository.Instance;

        static Aenderung_UST_Code_Konten instance = new Aenderung_UST_Code_Konten();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Aenderung_UST_Code_Konten()
        {
            UST_CD_NEU = "R77";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Aenderung_UST_Code_Konten Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable UST_CD_NEU.
        /// </summary>
        [TestVariable("f318fc56-2aa4-4257-9b49-17419e7449b3")]
        public string UST_CD_NEU
        {
            get { return repo.UST_CD_NEU; }
            set { repo.UST_CD_NEU = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TblUstVerwalten.Row_mit_UST_CD_NEU.ColUstSatz' at Center.", repo.TblUstVerwalten.Row_mit_UST_CD_NEU.ColUstSatzInfo, new RecordItemIndex(0));
            repo.TblUstVerwalten.Row_mit_UST_CD_NEU.ColUstSatz.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(1));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(2));
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(3));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='') on item 'TblUstVerwalten.Row_mit_UST_CD_NEU.ColUstAuft'.", repo.TblUstVerwalten.Row_mit_UST_CD_NEU.ColUstAuftInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.TblUstVerwalten.Row_mit_UST_CD_NEU.ColUstAuftInfo, "Text", "");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TblUstVerwalten.PbDataAccessSave' at Center.", repo.TblUstVerwalten.PbDataAccessSaveInfo, new RecordItemIndex(5));
            repo.TblUstVerwalten.PbDataAccessSave.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TblUstVerwalten.Row_mit_UST_CD_NEU.Column0' at Center.", repo.TblUstVerwalten.Row_mit_UST_CD_NEU.Column0Info, new RecordItemIndex(6));
            repo.TblUstVerwalten.Row_mit_UST_CD_NEU.Column0.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TblUstVerwalten.PbToolBarItemsKonten' at Center.", repo.TblUstVerwalten.PbToolBarItemsKontenInfo, new RecordItemIndex(7));
            repo.TblUstVerwalten.PbToolBarItemsKonten.Click();
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'TblUstk.TitleBar100UstKontoR77'", repo.TblUstk.TitleBar100UstKontoR77Info, new ActionTimeout(60000), new RecordItemIndex(8));
            repo.TblUstk.TitleBar100UstKontoR77Info.WaitForExists(60000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$UST_CD_NEU) on item 'TblUstk.TitleBar100UstKontoR77'.", repo.TblUstk.TitleBar100UstKontoR77Info, new RecordItemIndex(9));
            Validate.AttributeContains(repo.TblUstk.TitleBar100UstKontoR77Info, "Text", UST_CD_NEU);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2599') on item 'TblUstk.ColUstkVstkontoRow1'.", repo.TblUstk.ColUstkVstkontoRow1Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.TblUstk.ColUstkVstkontoRow1Info, "Text", "2599");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(11));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2530'.", new RecordItemIndex(12));
            Keyboard.Press("2530");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Tab' Press.", new RecordItemIndex(13));
            Keyboard.Press(System.Windows.Forms.Keys.Tab, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2530') on item 'TblUstk.ColUstkVstkontoRow1'.", repo.TblUstk.ColUstkVstkontoRow1Info, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.TblUstk.ColUstkVstkontoRow1Info, "Text", "2530");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TblUstk.PbDataAccessSave' at Center.", repo.TblUstk.PbDataAccessSaveInfo, new RecordItemIndex(15));
            repo.TblUstk.PbDataAccessSave.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Alt+F4' Press with focus on 'TblUstk.TitleBar100UstKontoR77'.", repo.TblUstk.TitleBar100UstKontoR77Info, new RecordItemIndex(16));
            Keyboard.PrepareFocus(repo.TblUstk.TitleBar100UstKontoR77);
            Keyboard.Press(System.Windows.Forms.Keys.F4 | System.Windows.Forms.Keys.Alt, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
