///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Z_PROJ_004.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The I_AUSFLUG_Phasen_aufrufen recording.
    /// </summary>
    [TestModule("02ee678d-0c38-4a1e-a7c1-a444215f77f0", ModuleType.Recording, 1)]
    public partial class I_AUSFLUG_Phasen_aufrufen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Z_PROJ_004.Z_PROJ_004Repository repository.
        /// </summary>
        public static global::Z_PROJ_004.Z_PROJ_004Repository repo = global::Z_PROJ_004.Z_PROJ_004Repository.Instance;

        static I_AUSFLUG_Phasen_aufrufen instance = new I_AUSFLUG_Phasen_aufrufen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public I_AUSFLUG_Phasen_aufrufen()
        {
            PROJ_NR_I_AUSFLUG_IP = "I-AUSFLUG";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static I_AUSFLUG_Phasen_aufrufen Instance
        {
            get { return instance; }
        }

#region Variables

        string _PROJ_NR_I_AUSFLUG_IP;

        /// <summary>
        /// Gets or sets the value of variable PROJ_NR_I_AUSFLUG_IP.
        /// </summary>
        [TestVariable("a4cdf375-d5cc-4624-ada2-a87df32dbcad")]
        public string PROJ_NR_I_AUSFLUG_IP
        {
            get { return _PROJ_NR_I_AUSFLUG_IP; }
            set { _PROJ_NR_I_AUSFLUG_IP = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FrmTabProjekt.TitleBar100ProjektVerwalten'.", repo.FrmTabProjekt.TitleBar100ProjektVerwaltenInfo, new RecordItemIndex(0));
            Validate.Exists(repo.FrmTabProjekt.TitleBar100ProjektVerwaltenInfo);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PROJ_NR_I_AUSFLUG_IP' with focus on 'FrmTabProjekt.Suche.Suchtext'.", repo.FrmTabProjekt.Suche.SuchtextInfo, new RecordItemIndex(1));
            repo.FrmTabProjekt.Suche.Suchtext.PressKeys(PROJ_NR_I_AUSFLUG_IP);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmTabProjekt.Suche.PbEdit' at Center.", repo.FrmTabProjekt.Suche.PbEditInfo, new RecordItemIndex(2));
            repo.FrmTabProjekt.Suche.PbEdit.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmTabProjekt.TabPagePhasen' at Center.", repo.FrmTabProjekt.TabPagePhasenInfo, new RecordItemIndex(3));
            repo.FrmTabProjekt.TabPagePhasen.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
