///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace B_JAHR_Schnelltest.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Neues_Jahr_loeschen recording.
    /// </summary>
    [TestModule("6ff3fb41-3b97-4fe1-b7c4-51c9e4403351", ModuleType.Recording, 1)]
    public partial class Neues_Jahr_loeschen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::B_JAHR_Schnelltest.B_JAHR_SchnelltestRepository repository.
        /// </summary>
        public static global::B_JAHR_Schnelltest.B_JAHR_SchnelltestRepository repo = global::B_JAHR_Schnelltest.B_JAHR_SchnelltestRepository.Instance;

        static Neues_Jahr_loeschen instance = new Neues_Jahr_loeschen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Neues_Jahr_loeschen()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Neues_Jahr_loeschen Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Jahr_NEU.
        /// </summary>
        [TestVariable("6bf11a9f-c841-4ec2-986d-1ffeb454e2ca")]
        public string Jahr_NEU
        {
            get { return repo.Jahr_NEU; }
            set { repo.Jahr_NEU = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Main_530_tblMain_510_frmMain.Tabelle_510_530.Column0_in_Zeile_mit_Jahr_NEU' at Center.", repo.Main_530_tblMain_510_frmMain.Tabelle_510_530.Column0_in_Zeile_mit_Jahr_NEUInfo, new RecordItemIndex(0));
            repo.Main_530_tblMain_510_frmMain.Tabelle_510_530.Column0_in_Zeile_mit_Jahr_NEU.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press with focus on 'Main_530_tblMain_510_frmMain.Tabelle_510_530.Column0_in_Zeile_mit_Jahr_NEU'.", repo.Main_530_tblMain_510_frmMain.Tabelle_510_530.Column0_in_Zeile_mit_Jahr_NEUInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.Main_530_tblMain_510_frmMain.Tabelle_510_530.Column0_in_Zeile_mit_Jahr_NEU);
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Main_530_tblMain_510_frmMain.PbStandard1' at Center.", repo.Main_530_tblMain_510_frmMain.PbStandard1Info, new RecordItemIndex(2));
            repo.Main_530_tblMain_510_frmMain.PbStandard1.Click();
            
            // search timeout reduziert auf 5s = eff 1min
            Report.Log(ReportLevel.Info, "Validation", "search timeout reduziert auf 5s = eff 1min\r\nValidating NotExists on item 'Main_530_tblMain_510_frmMain.Tabelle_510_530.Zeile_mit_Jahr_NEU'.", repo.Main_530_tblMain_510_frmMain.Tabelle_510_530.Zeile_mit_Jahr_NEUInfo, new RecordItemIndex(3));
            Validate.NotExists(repo.Main_530_tblMain_510_frmMain.Tabelle_510_530.Zeile_mit_Jahr_NEUInfo);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
