///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace B_BUOPPR_001.Recordings_Ausgabe
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Meldungen_LF1_Salden_Differenzen recording.
    /// </summary>
    [TestModule("76ad2ee0-954c-4f34-b884-eeb6a97a2629", ModuleType.Recording, 1)]
    public partial class Meldungen_LF1_Salden_Differenzen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::B_BUOPPR_001.B_BUOPPR_001Repository repository.
        /// </summary>
        public static global::B_BUOPPR_001.B_BUOPPR_001Repository repo = global::B_BUOPPR_001.B_BUOPPR_001Repository.Instance;

        static Meldungen_LF1_Salden_Differenzen instance = new Meldungen_LF1_Salden_Differenzen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Meldungen_LF1_Salden_Differenzen()
        {
            Meldung_Salden_DIFF_LF_1 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Meldungen_LF1_Salden_Differenzen Instance
        {
            get { return instance; }
        }

#region Variables

        string _Meldung_Salden_DIFF_LF_1;

        /// <summary>
        /// Gets or sets the value of variable Meldung_Salden_DIFF_LF_1.
        /// </summary>
        [TestVariable("1b7352ef-a4e8-4b2c-9502-d447ffd05460")]
        public string Meldung_Salden_DIFF_LF_1
        {
            get { return _Meldung_Salden_DIFF_LF_1; }
            set { _Meldung_Salden_DIFF_LF_1 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>$Meldung_Salden_DIFF_LF_1) on item 'DlgMessageBox.LabelMeldungstext'.", repo.DlgMessageBox.LabelMeldungstextInfo, new RecordItemIndex(0));
            Validate.AttributeContains(repo.DlgMessageBox.LabelMeldungstextInfo, "Text", Meldung_Salden_DIFF_LF_1);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DlgMessageBox.Button1_Nein' at Center.", repo.DlgMessageBox.Button1_NeinInfo, new RecordItemIndex(1));
            repo.DlgMessageBox.Button1_Nein.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
