///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace B_EXOPV_002.Recordings_B_BUAB
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The B_BUAB_Beleg4_pruefen recording.
    /// </summary>
    [TestModule("3f547595-3a61-4868-bdea-5abcbc6ed649", ModuleType.Recording, 1)]
    public partial class B_BUAB_Beleg4_pruefen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::B_EXOPV_002.B_EXOPV_002Repository repository.
        /// </summary>
        public static global::B_EXOPV_002.B_EXOPV_002Repository repo = global::B_EXOPV_002.B_EXOPV_002Repository.Instance;

        static B_BUAB_Beleg4_pruefen instance = new B_BUAB_Beleg4_pruefen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public B_BUAB_Beleg4_pruefen()
        {
            Beleg4 = "R20/0004";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static B_BUAB_Beleg4_pruefen Instance
        {
            get { return instance; }
        }

#region Variables

        string _Beleg4;

        /// <summary>
        /// Gets or sets the value of variable Beleg4.
        /// </summary>
        [TestVariable("46982a21-4c54-439b-bbe2-3ecad910b6d8")]
        public string Beleg4
        {
            get { return _Beleg4; }
            set { _Beleg4 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            // Zeile_3
            Report.Log(ReportLevel.Info, "Section", "Zeile_3", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$Beleg4) on item 'TblB.Buchungszeilen_Tabelle.Zeile3.ColBelegnrRow3'.", repo.TblB.Buchungszeilen_Tabelle.Zeile3.ColBelegnrRow3Info, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile3.ColBelegnrRow3Info, "Text", Beleg4);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1.200,00') on item 'TblB.Buchungszeilen_Tabelle.Zeile3.ColBetragRow3'.", repo.TblB.Buchungszeilen_Tabelle.Zeile3.ColBetragRow3Info, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile3.ColBetragRow3Info, "Text", "1.200,00");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='10 +') on item 'TblB.Buchungszeilen_Tabelle.Zeile3.ColCd1Row3'.", repo.TblB.Buchungszeilen_Tabelle.Zeile3.ColCd1Row3Info, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile3.ColCd1Row3Info, "Text", "10 +");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='100 +') on item 'TblB.Buchungszeilen_Tabelle.Zeile3.ColCd3Row3'.", repo.TblB.Buchungszeilen_Tabelle.Zeile3.ColCd3Row3Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile3.ColCd3Row3Info, "Text", "100 +");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TX001-21001 +') on item 'TblB.Buchungszeilen_Tabelle.Zeile3.ColCd4Row3'.", repo.TblB.Buchungszeilen_Tabelle.Zeile3.ColCd4Row3Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile3.ColCd4Row3Info, "Text", "TX001-21001 +");
            
            // Zeile_4
            Report.Log(ReportLevel.Info, "Section", "Zeile_4", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='10 +') on item 'TblB.Buchungszeilen_Tabelle.Zeile_4.ColCd1Row4'.", repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColCd1Row4Info, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColCd1Row4Info, "Text", "10 +");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='100 +') on item 'TblB.Buchungszeilen_Tabelle.Zeile_4.ColCd3Row4'.", repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColCd3Row4Info, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColCd3Row4Info, "Text", "100 +");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='TX001-21001 +') on item 'TblB.Buchungszeilen_Tabelle.Zeile_4.ColCd4Row4'.", repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColCd4Row4Info, new RecordItemIndex(9));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColCd4Row4Info, "Text", "TX001-21001 +");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='QS') on item 'TblB.Buchungszeilen_Tabelle.Zeile_4.ColKtbeNrRow4'.", repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColKtbeNrRow4Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColKtbeNrRow4Info, "Text", "QS");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='M20') on item 'TblB.Buchungszeilen_Tabelle.Zeile_4.ColUstcdRow4'.", repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColUstcdRow4Info, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColUstcdRow4Info, "Text", "M20");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='1') on item 'TblB.Buchungszeilen_Tabelle.Zeile_4.ColUstmvRow4'.", repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColUstmvRow4Info, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColUstmvRow4Info, "Text", "1");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='200,00') on item 'TblB.Buchungszeilen_Tabelle.Zeile_4.ColUstbetragRow4'.", repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColUstbetragRow4Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColUstbetragRow4Info, "Text", "200,00");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2020-1') on item 'TblB.Buchungszeilen_Tabelle.Zeile_4.ColUvaRow4'.", repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColUvaRow4Info, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.TblB.Buchungszeilen_Tabelle.Zeile_4.ColUvaRow4Info, "Text", "2020-1");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
