///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace N_ANLA_004.Recordings
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Zuruecksetzen_GJ recording.
    /// </summary>
    [TestModule("a6668a8d-0bcd-4990-90ed-c82e5551c178", ModuleType.Recording, 1)]
    public partial class Zuruecksetzen_GJ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::N_ANLA_004.N_ANLA_004Repository repository.
        /// </summary>
        public static global::N_ANLA_004.N_ANLA_004Repository repo = global::N_ANLA_004.N_ANLA_004Repository.Instance;

        static Zuruecksetzen_GJ instance = new Zuruecksetzen_GJ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Zuruecksetzen_GJ()
        {
            GJ = "2023";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Zuruecksetzen_GJ Instance
        {
            get { return instance; }
        }

#region Variables

        string _GJ;

        /// <summary>
        /// Gets or sets the value of variable GJ.
        /// </summary>
        [TestVariable("613698ba-497d-4ee8-b3d2-3b126d8a1816")]
        public string GJ
        {
            get { return _GJ; }
            set { _GJ = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmAnfi.ClientArea.PbGjhrAktuell' at Center.", repo.FrmAnfi.ClientArea.PbGjhrAktuellInfo, new RecordItemIndex(0));
            repo.FrmAnfi.ClientArea.PbGjhrAktuell.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2022{Tab}' with focus on 'FrmAnfi.ClientArea.DfGjhrBez'.", repo.FrmAnfi.ClientArea.DfGjhrBezInfo, new RecordItemIndex(1));
            repo.FrmAnfi.ClientArea.DfGjhrBez.PressKeys("2022{Tab}");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='2022') on item 'FrmAnfi.ClientArea.DfGjhrBez'.", repo.FrmAnfi.ClientArea.DfGjhrBezInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.FrmAnfi.ClientArea.DfGjhrBezInfo, "Text", "2022");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmAnfi.PbDataAccessSave' at Center.", repo.FrmAnfi.PbDataAccessSaveInfo, new RecordItemIndex(3));
            repo.FrmAnfi.PbDataAccessSave.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
