name: API Automation
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - API_Automation_Cypress
    exclude:
    - .pipelines
    - 510
    - Hotfixtest
    - URS_TST

resources:
- repo: self

pool:
  vmImage: 'windows-latest'
  pool:
   name: Automation
   demands:
     - agent.name -equals DGA1APP03RNSQA


steps:
   - task: DownloadBuildArtifacts@1
     inputs:
      buildType: 'specific'
      project: '1692ec27-30a7-44ac-bb45-41f0b3ec9f01'
      pipeline: '99'
      buildVersionToDownload: 'specific'
      buildId: '$(buildId)'
      downloadType: 'single'
      artifactName: 'RS2Build'
      downloadPath: '$(System.ArtifactsDirectory)'

   - task: PowerShell@2
     displayName: 'Run Service Host'
     inputs:
      targetType: 'inline'
      script: |
        Start-Process -FilePath "$(System.DefaultWorkingDirectory)\API_Automation_Cypress\BatchFile\ServiceHost.bat" -WindowStyle Hidden

   - task: CmdLine@2
     displayName: 'NPM initialization'
     inputs:
       script: |
        npm install
        npm i   
       workingDirectory: '$(System.DefaultWorkingDirectory)/API_Automation_Cypress/Modulewise_TestCases'

   - task: BatchScript@1
     displayName: 'Run Cypress Scripts'
     inputs:
      filename: '$(System.DefaultWorkingDirectory)/API_Automation_Cypress/BatchFile/RunScripts.bat'

   - task: ArchiveFiles@2
     condition: AND(succeededOrFailed(),ne(canceled(), 'true'))
     inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)\API_Automation_Cypress\Modulewise_TestCases\cypress\reports'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(System.DefaultWorkingDirectory)\API_Automation_Cypress\Modulewise_TestCases\cypress\reports.zip'
      replaceExistingArchive: true

  # - task: SendEmail@1
  #   condition: AND(succeededOrFailed(),ne(canceled(), 'true'))
  #   inputs:
  #    To: 'kishore.ramachandraiah@aptean.com'
  #    From: '$(SMTP_MailID)'
  #    Subject: 'RS2 Automation reports'
  #    Body: |
  #          This is the body of the email. You can write your content here and use proper alignment.
                 
  #                         Thank you,
  #                         Your Name
  #    BodyAsHtml: false
  #    AddAttachment: true
  #    Attachment: '$(System.DefaultWorkingDirectory)\API_Automation_Cypress\Modulewise_TestCases\cypress\reports.zip'
  #    SmtpServer: 'smtp.office365.com'
  #    SmtpUsername: '$(SMTP_UserName)'
  #    SmtpPassword: '$(SMTP_UserPassword)'

   - task: SendEmail@1
     condition: AND(succeededOrFailed(),ne(canceled(), 'true'))
     inputs:
      To: 'kishore.ramachandraiah@aptean.com'
      From: 'ApteanOperations-.RSautomation@aptean.com'
      Subject: 'RS2 Automation reports'
      Body: |
        This is the body of the email. You can write your content here and use proper alignment.
                         
                                  Thank you,
                                  Your Name
      BodyAsHtml: false
      SmtpServer: 'smtp.office365.com'
      AddAttachment: true
      Attachment: '$(System.DefaultWorkingDirectory)\API_Automation_Cypress\Modulewise_TestCases\cypress\reports.zip'
      SmtpUsername: '$(SMTP_UserName)'
      SmtpPassword: '$(SMTP_UserPassword)'



    
