///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace B_ELSTER_005.Recordings_notepad
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Pruefung_Inhalt_XML_JUVA_Umsaetze_2022 recording.
    /// </summary>
    [TestModule("a7ff2848-0ddb-4032-b8ec-8560f6aeb3c2", ModuleType.Recording, 1)]
    public partial class Pruefung_Inhalt_XML_JUVA_Umsaetze_2022 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::B_ELSTER_005.B_ELSTER_005Repository repository.
        /// </summary>
        public static global::B_ELSTER_005.B_ELSTER_005Repository repo = global::B_ELSTER_005.B_ELSTER_005Repository.Instance;

        static Pruefung_Inhalt_XML_JUVA_Umsaetze_2022 instance = new Pruefung_Inhalt_XML_JUVA_Umsaetze_2022();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Pruefung_Inhalt_XML_JUVA_Umsaetze_2022()
        {
            XML_JUVA_2021_IG = "";
            XML_JUVA_2021_Umsaetze_stfrei = "";
            XML_JUVA_2021_13a_drei = "";
            XML_JUVA_2021_abz_Vst = "";
            XML_JUVA_2021_Ber_Vst_15a = "";
            XML_JUVA_2021_Umsaetze = "";
            XML_JUVA_2022_Umsaetze_LuF = "";
            XML_JUVA_2022_13b_Erg = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Pruefung_Inhalt_XML_JUVA_Umsaetze_2022 Instance
        {
            get { return instance; }
        }

#region Variables

        string _XML_JUVA_2021_IG;

        /// <summary>
        /// Gets or sets the value of variable XML_JUVA_2021_IG.
        /// </summary>
        [TestVariable("a5857302-2912-4e2e-b70c-68837366f7ef")]
        public string XML_JUVA_2021_IG
        {
            get { return _XML_JUVA_2021_IG; }
            set { _XML_JUVA_2021_IG = value; }
        }

        string _XML_JUVA_2021_Umsaetze_stfrei;

        /// <summary>
        /// Gets or sets the value of variable XML_JUVA_2021_Umsaetze_stfrei.
        /// </summary>
        [TestVariable("1abc97ad-ad40-45d3-9ae9-9dec1e02c48c")]
        public string XML_JUVA_2021_Umsaetze_stfrei
        {
            get { return _XML_JUVA_2021_Umsaetze_stfrei; }
            set { _XML_JUVA_2021_Umsaetze_stfrei = value; }
        }

        string _XML_JUVA_2021_13a_drei;

        /// <summary>
        /// Gets or sets the value of variable XML_JUVA_2021_13a_drei.
        /// </summary>
        [TestVariable("2a49c13c-04de-4c7d-81af-7999beb0483b")]
        public string XML_JUVA_2021_13a_drei
        {
            get { return _XML_JUVA_2021_13a_drei; }
            set { _XML_JUVA_2021_13a_drei = value; }
        }

        string _XML_JUVA_2021_abz_Vst;

        /// <summary>
        /// Gets or sets the value of variable XML_JUVA_2021_abz_Vst.
        /// </summary>
        [TestVariable("902c7c2f-15f1-4166-8339-1841a6f5e64c")]
        public string XML_JUVA_2021_abz_Vst
        {
            get { return _XML_JUVA_2021_abz_Vst; }
            set { _XML_JUVA_2021_abz_Vst = value; }
        }

        string _XML_JUVA_2021_Ber_Vst_15a;

        /// <summary>
        /// Gets or sets the value of variable XML_JUVA_2021_Ber_Vst_15a.
        /// </summary>
        [TestVariable("f2b8e73b-05cb-40f6-8cc6-c26b35122fc2")]
        public string XML_JUVA_2021_Ber_Vst_15a
        {
            get { return _XML_JUVA_2021_Ber_Vst_15a; }
            set { _XML_JUVA_2021_Ber_Vst_15a = value; }
        }

        string _XML_JUVA_2021_Umsaetze;

        /// <summary>
        /// Gets or sets the value of variable XML_JUVA_2021_Umsaetze.
        /// </summary>
        [TestVariable("6143b75b-e8c8-455b-8237-b8d0d21a37e0")]
        public string XML_JUVA_2021_Umsaetze
        {
            get { return _XML_JUVA_2021_Umsaetze; }
            set { _XML_JUVA_2021_Umsaetze = value; }
        }

        string _XML_JUVA_2022_Umsaetze_LuF;

        /// <summary>
        /// Gets or sets the value of variable XML_JUVA_2022_Umsaetze_LuF.
        /// </summary>
        [TestVariable("535049dc-c6fa-404e-8f40-3073ee306d01")]
        public string XML_JUVA_2022_Umsaetze_LuF
        {
            get { return _XML_JUVA_2022_Umsaetze_LuF; }
            set { _XML_JUVA_2022_Umsaetze_LuF = value; }
        }

        string _XML_JUVA_2022_13b_Erg;

        /// <summary>
        /// Gets or sets the value of variable XML_JUVA_2022_13b_Erg.
        /// </summary>
        [TestVariable("59d7ad19-abbe-49e5-8eb9-11cde37c8dfc")]
        public string XML_JUVA_2022_13b_Erg
        {
            get { return _XML_JUVA_2022_13b_Erg; }
            set { _XML_JUVA_2022_13b_Erg = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>$XML_JUVA_2021_Umsaetze) on item 'XMLEditor_UVA_ZM.Text15'.", repo.XMLEditor_UVA_ZM.Text15Info, new RecordItemIndex(0));
                Validate.AttributeContains(repo.XMLEditor_UVA_ZM.Text15Info, "Text", XML_JUVA_2021_Umsaetze, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>$XML_JUVA_2022_Umsaetze_LuF) on item 'XMLEditor_UVA_ZM.Text15'.", repo.XMLEditor_UVA_ZM.Text15Info, new RecordItemIndex(1));
                Validate.AttributeContains(repo.XMLEditor_UVA_ZM.Text15Info, "Text", XML_JUVA_2022_Umsaetze_LuF, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>$XML_JUVA_2021_Umsaetze_stfrei) on item 'XMLEditor_UVA_ZM.Text15'.", repo.XMLEditor_UVA_ZM.Text15Info, new RecordItemIndex(2));
                Validate.AttributeContains(repo.XMLEditor_UVA_ZM.Text15Info, "Text", XML_JUVA_2021_Umsaetze_stfrei, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>$XML_JUVA_2021_IG) on item 'XMLEditor_UVA_ZM.Text15'.", repo.XMLEditor_UVA_ZM.Text15Info, new RecordItemIndex(3));
                Validate.AttributeContains(repo.XMLEditor_UVA_ZM.Text15Info, "Text", XML_JUVA_2021_IG, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>$XML_JUVA_2021_13a_drei) on item 'XMLEditor_UVA_ZM.Text15'.", repo.XMLEditor_UVA_ZM.Text15Info, new RecordItemIndex(4));
                Validate.AttributeContains(repo.XMLEditor_UVA_ZM.Text15Info, "Text", XML_JUVA_2021_13a_drei, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>$XML_JUVA_2022_13b_Erg) on item 'XMLEditor_UVA_ZM.Text15'.", repo.XMLEditor_UVA_ZM.Text15Info, new RecordItemIndex(5));
                Validate.AttributeContains(repo.XMLEditor_UVA_ZM.Text15Info, "Text", XML_JUVA_2022_13b_Erg, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>$XML_JUVA_2021_abz_Vst) on item 'XMLEditor_UVA_ZM.Text15'.", repo.XMLEditor_UVA_ZM.Text15Info, new RecordItemIndex(6));
                Validate.AttributeContains(repo.XMLEditor_UVA_ZM.Text15Info, "Text", XML_JUVA_2021_abz_Vst, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>$XML_JUVA_2021_Ber_Vst_15a) on item 'XMLEditor_UVA_ZM.Text15'.", repo.XMLEditor_UVA_ZM.Text15Info, new RecordItemIndex(7));
                Validate.AttributeContains(repo.XMLEditor_UVA_ZM.Text15Info, "Text", XML_JUVA_2021_Ber_Vst_15a, null, false);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(7)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
